### ISSUE TITLE
Devtools won't let me work!

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#1013]
Hello Team,

I just get this mesage on email from a customer:

"Hello, excuse me.
It seems to be an error in the provider's server.
I had to get a new server to install backpack temporarily, but Devtools won't let me work."

https://github.com/Laravel-Backpack/community-forum/assets/144793034/2a5aeb9c-3aa8-4e9c-a5af-ced2b9b26d37

**Comment by djcrisspty** [comment]
Hi, the problem is that the action buttons do nothing. It does not allow to add anything.

**Comment by djcrisspty** [comment]
I solved the problem. The problem was that I could not find livewire.
