### ISSUE TITLE
Hi @jcastroa87 ,

### ISSUE THREAD

**Issue by AlonMoshe** [Laravel-Backpack/community-forum#1017]
Hi @jcastroa87 ,

I am working on my project and I followed your suggestion. However, the field that I need to change is a date time, so I need to wait for the user to fish selecting the date and time.  

The problem I am having with:

```
crud.field("project_id")
    .onChange(function (field) {................

```
Is that it executes for every change the user makes. Which is not the behaviour that I need. I need the Ajax call to be done after the user has finished entering the date and time

Since in [the documention](https://backpackforlaravel.com/docs/6.x/crud-fields-javascript-api#syntax-1) it is written that it is possible to use plain JavaScript and JQuery, I am trying the following:

1. In the setupCreateOperation I added :

 ```
 Widget::add([
            'type' =>'script',
            'content'=> 'assets/js/admin/forms/myfile.js',
        ]);
```

3. In the JS file I have:

```
var formId=document.forms[0];
var startTimeElement=formId.querySelector('input[name="startTime"]');
     startTimeElement.addEventListener('blur',handleBlur);

function handleBlur(event){
 // Ajax call 
alert('This is a test')
}
```

Unfortunately, so far the "handleBlur" function doesn't even get called, I  do not know why. 

I will appreciate it if you have any suggestions/observations.

Once again, many thanks.

Alon.

_Originally posted by @AlonMoshe in https://github.com/Laravel-Backpack/community-forum/discussions/1005#discussioncomment-9718327_

**Comment by jcastroa87** [comment]
Hello @AlonMoshe 

I made a test. Is working in my side:

I use our demo:

<img width="577" alt="Screenshot 2024-06-10 at 11 55 17 AM" src="https://github.com/Laravel-Backpack/community-forum/assets/44643608/cc1c5a92-c2b3-44d7-a65a-09e31f758e50">

Then add the script:

<img width="691" alt="Screenshot 2024-06-10 at 11 56 14 AM" src="https://github.com/Laravel-Backpack/community-forum/assets/44643608/d02a49fc-9abb-4864-810c-5cab28bdb632">

And there is the event:

<img width="1335" alt="Screenshot 2024-06-10 at 11 56 57 AM" src="https://github.com/Laravel-Backpack/community-forum/assets/44643608/4cbfbe44-0d9e-46b7-95c1-01bc78d6ee63">

Cheers.
