### ISSUE TITLE
[Feature Request] Ability for buttons to load global JS

### ISSUE THREAD

**Issue by WrdVdb** [Laravel-Backpack/community-forum#102]
# Feature Request

We have records that cannot be deleted by a specific user.
Some records can be deleted, some cannot.

We would like to have a option to show or hide the default actions record per record.

![image](https://user-images.githubusercontent.com/36230484/102986998-ff01ca00-4511-11eb-859c-4afabca04369.png)

### What's the feature you think Backpack should have?

Make it possible to hide a default action button with a method in the model. Or add the deleteEntry javascript globally (see below)

### Have you already implemented a prototype solution, for your own project?

I tried to hide the default delete button, and add a custom one. This works fine (see screenshot), but then the javascript "deleteEntry" seems to be added in de delete button view. This javascript is also repeated with each delete button. This seams strange, 80 lines of javascript per delete button. And only the first is called because of 

`if (typeof deleteEntry != 'function') { ...`

Is it possible to add the deleteEntry javascript code globally, and remove this from the delete button blade file?

**Comment by realtebo** [comment]
I add a related feature request: show/hide delete button based on an attribute of the model.

Scenario: hide delete of a parent model if it has childrens.

**Comment by tabacitu** [comment]
Hmm... I'm not sure the Model is a good place to define that bit of logic. Since it would only have effects inside the CRUD, it should probably live in the ProductCrudController or a related blade file. Otherwise we risk bloating up the Model with things that are not exactly reusable, just slightly related to the model.

**Comment by realtebo** [comment]
No.. I don't want to touch the model class.

Imagine I've a simply flag on my model.

I can delete only if the flag is true.

I suggest to pass a callback that is receiving the model of the line, so if the callback returns true, the button is showed.

Simlarry, in my exact case, I must chech if $model->relation_name->count() > 0 to allow deleting.

**Comment by promatik** [comment]
I like the idea of simplifying disabling the buttons with a closure.

A wider solution could be something like;

```php
$this->crud->setButtonAttributes('delete', [
    'title' => 'Delete entry',
    // to disable
    'disabled' => function ($entry) {
        return $entry->articles()->count() > 0;
    },
    // or to hide
    'class' => function ($entry) {
        return $entry->articles()->count() > 0 ? "d-none" : "";
    },
]);
```

**Comment by tabacitu** [comment]
Worth considering. Problem for future us though - let's return to this after we've finished what's on our plate for 4.1 😉

**Comment by pxpm** [comment]
This is already done. 
```php
CRUD::setAccessCondition(['update', 'delete'], function ($entry) {
    return backpack_user()->isSuperAdmin() ? true : false;
});
```
Better than just hidding the buttons, it also blocks the actions (even if user access via url).
