### ISSUE TITLE
Issues "Calendar Operation backpack/calendar-operation"

### ISSUE THREAD

**Issue by NeguinhoAdmin** [Laravel-Backpack/community-forum#1033]
Issues "Calendar Operation backpack/calendar-operation"

Hi, 

I already certain that my timezone is okay, it is not UTC it is :     'timezone' => 'Europe/London',

But problem is when I click visual slot it change 1 hour difference on datetime inputs in form. I hope gif file helps to visually look at the problem.

futhermore the same problem is in demo site

![pic](https://github.com/Laravel-Backpack/community-forum/assets/136070103/d9c82f46-ef86-4f8d-a66c-05c4d8775b3c)

Thank you

**Comment by jcastroa87** [comment]
I confirm the issue, i will ask @pxpm to check this.

Thanks for give us this information.

Cheers.

**Comment by ShariqAyaz** [comment]
Also add feature that business start and end timing.
Sunday no booking.

One more thing how i get updates when issues fixed

**Comment by ShariqAyaz** [comment]
This issue solved by this:
        $start = request()->has('start') ? Carbon::parse(request('start'))->setTimezone(config('app.timezone')) : null;
        $end = request()->has('end') ? Carbon::parse(request('end'))->setTimezone(config('app.timezone')) : null;

its mean that in someway, javascript keeping diff. timezone.

**Comment by jcastroa87** [comment]
Im glad you solve the problem. I will close this issue, but please feel free to re-open or create a new one if needed.

Cheers.
