### ISSUE TITLE
[Bug] Call to a member function withFakes() on bool 

### ISSUE THREAD

**Issue by allam2002** [Laravel-Backpack/community-forum#1053]
# Bug report
Call to a member function withFakes() on bool , in backpack editable columns. 3.0.9
### What I did
i checked my my version
??
BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.3
backpack/basset: 1.3.4
backpack/crud: 6.7.17
backpack/devtools: 2.0.3
backpack/editable-columns: 3.0.9
backpack/filemanager: 3.0.8
backpack/generators: v4.0.5
backpack/logmanager: v5.0.2
backpack/medialibrary-uploaders: 1.2.0
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.4
backpack/revise-operation: 2.0.0
backpack/theme-tabler: 1.2.10
### What I expected to happen

??

### What happened

??

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by karandatwani92** [comment]
Hey @allam2002 

Our [demo](https://demo.backpackforlaravel.com/admin/editable-monster) uses `editable-columns: 3.0.9`. I see no issue there. Can you check on your end or tell us the steps to reproduce the error?
