### ISSUE TITLE
[Bug] Assistance Required for Installing Backpack Calendar Operation Package

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#1079]
Hello team, 

I just received this message

 on email:

",Dear Backpack Support Team
I hope this message finds you well.

I am currently evaluating the packages included in my Backpack subscription and have encountered issues while attempting to install the calendar-operation package, among others. Despite following the provided instructions and making several attempts, I have been unable to successfully install the package.

Here are the steps I have taken so far:

Added Authentication for Backpack: I have configured the authentication for Backpack using the following command:

composer config --global --auth [http-basic.repo.backpackforlaravel.com](http://http-basic.repo.backpackforlaravel.com/) <my-username> <my-backpack-token>
Added Authentication for GitHub: I have also set up the authentication for GitHub using the command:
composer config --global --auth [github-oauth.github.com](http://github-oauth.github.com/)  my-github-token

Updated composer.json File: I have ensured that the composer.json file includes the Backpack repository as follows:  
{ "repositories": [ { "type": "composer", "url": "https://repo.backpackforlaravel.com/" } ] }
Installation Attempt: I have attempted to install the calendar-operation package using the command:

composer require backpack/calendar-operation

Despite these efforts, I consistently receive an error indicating that the package could not be found or accessed. Attached is a screenshot of the error message for your reference.
I would greatly appreciate your assistance in resolving this issue, as I am keen to utilize the full range of Backpack’s functionalities.

Thank you for your time and support.
![234233](https://github.com/Laravel-Backpack/community-forum/assets/144793034/06d80478-0a4b-4032-9dfd-e8f9d21ec05c)"

**Comment by karandatwani92** [comment]
Hey @backpack-operations 

Can you visit this [page](https://backpackforlaravel.com/user/tokens) and check under the `packages` tab that you have access to the `calendar-operation` package? It should look like this:
![Screenshot 2024-07-12 at 1 26 56 PM](https://github.com/user-attachments/assets/f3d1da8e-3410-4bb4-85be-472a538e3882)

**Comment by tabacitu** [comment]
Heads-up, ERROR 400 when trying to download a closed-source package means "user and password do not match". You can see all error codes and their meanings here - https://backpackforlaravel.com/docs/6.x/faq#errors-when-installing-paid-add-ons
