### ISSUE TITLE
[Feature Request] Table Widget - Same as the CRUD table list view

### ISSUE THREAD

**Issue by lambasoft** [Laravel-Backpack/community-forum#108]
# Feature Request

### What's the feature you think Backpack should have?

I'm in need of a widget that shows a table of data fetched from a controller, in a same table view as the table in CRUD pages. I need the filter, search and sorting functionalities..

currently the widget does not exist, and I believe it's not an easy task to make it available as a Widget?

**Comment by promatik** [comment]
Hi @lambasoft is this related with https://github.com/Laravel-Backpack/ideas/issues/108?

**Comment by tabacitu** [comment]
Good news - This is one of the most requested features in Backpack, so we're going to make it a priority in v6 🎉 Let's move the conversation to https://github.com/Laravel-Backpack/community-forum/issues/100 where I think it's better defined.
