### ISSUE TITLE
[Bug] unexpected Composer authorization request when trying to upgrade backpack/pro to version higher than 2.2.4

### ISSUE THREAD

**Issue by vernar** [Laravel-Backpack/community-forum#1087]
# Bug report

### What I did

1. use correct  credentials  in  auth.json
2. set version in composer.json  -  "backpack/pro": "^2.0"
3. run `composer upgrade` command 

### What I expected to happen
 Downloading  backpack/pro (2.2.8)  
and installed successfully 

### What happened
composer ask for token credentials to access private repos
![Выделение_084](https://github.com/user-attachments/assets/303393c6-80f8-4242-877b-223f20160d68)

### What I've already tried to fix it
if I set version  "backpack/pro": "2.2.4"  clear(or not) composer cache, remove (or not) vendor folder,  or run composer upgrade on other device, all installed correct without git access 

### Is it a bug in the latest version of Backpack?
It were reproduced on 2.2.5, 2.2.6, 2.2.7,  2.2.8 versions

#### PHP VERSION:
8.2.21

#### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, imagick, intl, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache, xdebug

#### LARAVEL VERSION:
10.48.16.0

#### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.5
backpack/crud: 6.7.18
backpack/generators: v4.0.5
backpack/logmanager: v5.0.2
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.4
backpack/settings: 3.1.1
backpack/theme-coreuiv2: 1.2.5
backpack/theme-coreuiv4: 1.1.2

**Comment by pxpm** [comment]
Hello @vernar 

usually 402 means payment required. So it's possible that your license expired in backpack/pro:2.2.4, so you have access to that version and all prior versions to that one but not newer versions. 

You can check what versions and until when you have package updates by login into your account at https://backpackforlaravel.com/user/tokens . 

Let me know if I can help you with something else 👍 

Cheers

**Comment by jcastroa87** [comment]
Due to not activity i will close this issue, but please feel free to re-open or create a new one if needed.

Cheers.
