### ISSUE TITLE
[Bug] vendor/backpack/crud/src/resources/views/crud/buttons/update.blade.php

### ISSUE THREAD

**Issue by blondie63** [Laravel-Backpack/community-forum#1105]
This is only aesthetic defect !
In this update.blade.php at rows 6 & 14 there are two wrong spaces
Correct is: <span><i class="la la-edit"></i>{{ trans('backpack::crud.edit') }}</span>

### PHP VERSION:
8.3.9

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, FFI, fileinfo, filter, ftp, gd, gettext, gmp, json, iconv, intl, SPL, ldap, mbstring, session, standard, odbc, pcntl, exif, mysqlnd, PDO, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, random, readline, Reflection, mysqli, shmop, SimpleXML, soap, sockets, sodium, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, xdebug, Zend OPcache

### LARAVEL VERSION:
11.19.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.5
backpack/crud: 6.7.24
backpack/devtools: 3.1.5
backpack/editable-columns: 3.0.10
backpack/generators: v4.0.5
backpack/language-switcher: 2.0.0
backpack/pro: 2.2.11
backpack/settings: 3.1.1
backpack/theme-coreuiv2: 1.2.5

**Comment by jcastroa87** [comment]
Hello @blondie63 

I cant see the spaces you point, can you show me in the file https://github.com/Laravel-Backpack/CRUD/blob/main/src/resources/views/crud/buttons/update.blade.php

![image](https://github.com/user-attachments/assets/09dba2f3-a16d-49cc-b60d-4a3d78b851be)

Thanks.

Cheers.

**Comment by blondie63** [comment]
![bkpSpace](https://github.com/user-attachments/assets/1650f6ae-8657-4f2b-888d-834345206d60)

but maybe all you buttons have this space..
i think is better without but anyway.. :)

**Comment by jcastroa87** [comment]
As you say, all the buttons use this space from icon.

Cheers.
