### ISSUE TITLE
Visual Bug on backpack-laravel Calendar 

### ISSUE THREAD

**Issue by NeguinhoAdmin** [Laravel-Backpack/community-forum#1141]
Hi Team,

Problem One is as picture shown: we click on slot on the desire day but the context menu appear two days ahead. It became more problem when booking slot on last day of week. 
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/b7b910b9-9e94-4d66-8081-d9104ee65873">

Secondly, bring hover effect because it hard to keep track visually to which time slot is being hover.

Thank you.

**Comment by NeguinhoAdmin** [comment]
I have just update it shows 1.0.7 version.

<img width="601" alt="image" src="https://github.com/user-attachments/assets/a9f7c8b7-3b76-4399-b920-b3c1de119443">

**Comment by pxpm** [comment]
Hey @NeguinhoAdmin allow a little bit of time for our private repository to pick the changes. 

You can try again in a few moments and you should get 1.0.8. 👍 

Cheers
