### ISSUE TITLE
[Bug] Issue with testing PRO on a subdomain

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#1151]
Hello team,

I just received this on email, please take a look!

"I'm having an issue testing this on a subdomain. The primary domain I used when purchasing is [odgaz.odessa.ua](http://odgaz.odessa.ua/). I set up the development environment on [dev.odgaz.odessa.ua](http://dev.odgaz.odessa.ua/), but it seems like it's not working correctly. It's trying to pull assets from the primary domain instead of the subdomain: https://dev.odgaz.odessa.ua/og-admin/login"
![Screenshot_1](https://github.com/user-attachments/assets/96fcd165-37f6-4f6d-8813-135f79187a6e)

**Comment by karandatwani92** [comment]
Hey @backpack-operations 

Can you check the following values in the `.env`:
```
APP_URL=https://dev.odgaz.odessa.ua
ASSET_URL=https://dev.odgaz.odessa.ua
```
