### ISSUE TITLE
CalendarOperation drag drop updates wrong time.

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/community-forum#1156]
### Discussed in https://github.com/Laravel-Backpack/community-forum/discussions/1155

<div type='discussions-op-text'>

<sup>Originally posted by **Sladous** September 17, 2024</sup>
Hi,
I purchased Backpack\CalendarOperation and am experiencing several issues with it:
1) Not even on the demo
https://demo.backpackforlaravel.com/admin/meeting/calendar
saving mouse changes does not work correctly.
If the all-day event is moved back one day, the system returns "Event updated successfully", but after reloading the page, the event is moved back one day.

2) It is not allowed to comment:
// use \Backpack\CRUD\app\Http\Controllers\Operations\ShowOperation;
Because the context menu doesn't work otherwise.
I solve:
 $this->crud->removeButton('show');

3) I don't know how to set Monday as the first day of the week.
Could this be related to point 1?</div>

**Comment by pxpm** [comment]
This should be fixed in `backpack/calendar-operation` v1.0.8

Cheers
