### ISSUE TITLE
[Bug]  Problem with Modal Button

### ISSUE THREAD

**Issue by helesjunior** [Laravel-Backpack/community-forum#1158]
# Bug report

### What I did  
Hey guys,

Today I came across a small problem. I use the theme-coreuiv2 theme in Backpack 6.x, and I'm having trouble creating a modal button. When I click on the button I cannot enable the modal to use and block the screen.

```
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
    Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
``` 

![image](https://github.com/user-attachments/assets/b6bfb001-e1b5-494e-8055-491f8bb62e24)

### PHP VERSION:
8.3.10

### PHP EXTENSIONS:
Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, random, readline, Reflection, session, standard, mysqlnd, tokenizer, zlib, libxml, dom, PDO, openssl, 
SimpleXML, xml, xmlreader, xmlwriter, ldap, curl, fileinfo, gd, gettext, gmp, intl, imap, mbstring, mysqli, odbc, Phar, pdo_mysql, PDO_ODBC, pdo_pgsql, pgsql, shmop, sqlsrv, pdo_sqlsrv, soap, sqlite3, xsl, zip, Zend OPcache

### LARAVEL VERSION:
11.20.0.0

### BACKPACK PACKAGE VERSIONS:  
backpack/activity-log: 2.0.4
backpack/basset: 1.3.5
backpack/crud: 6.7.26
backpack/generators: v4.0.5
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.13
backpack/theme-coreuiv2: 1.2.5

**Comment by karandatwani92** [comment]
Hey @helesjunior 
Sorry for the inconvenience. I'm assigning my colleague to fix the issue. Thanks for reporting.

@pxpm 
I tested on all three themes. Here is how it is behaving on a sample bootstrap [modal](https://getbootstrap.com/docs/5.3/components/modal/#live-demo):
- Tabler:  Modal pops up, but `modal-backdrop` z-index is high which is blocking the UI.
- CoreUi-v4:  Modal pops up, but the `modal-backdrop` z-index is high which is blocking the UI.
- CoreUi-v2:  No Modal pops-up.

**Comment by pxpm** [comment]
Most likely you need to append your modal to the end of the body, and not leave it where the button is placed. 

So with a bit of javascript you should be able to select the modal by id, and then append it to the body. 

That's what we do for `inlineCreate`: 
![image](https://github.com/user-attachments/assets/80808af8-3a37-4895-a770-7f7a6b2b2d44)

We get the modal html (result), and append it to the body before triggering the modal open. 

Let me know if that helps 👍
