### ISSUE TITLE
Custom Views (for ListOperation) - View not showing

### ISSUE THREAD

**Issue by Read2uk** [Laravel-Backpack/community-forum#1174]
### Discussed in https://github.com/Laravel-Backpack/community-forum/discussions/1173

<div type='discussions-op-text'>

<sup>Originally posted by **Read2uk** October  1, 2024</sup>
Hi all,

Just a quick question, not sure if I am doing something wrong. Basically want to add Custom Views but the dropdown button is not showing the added views (is not clickable on the dropdown)

This is what the CrudController looks like:

![image](https://github.com/user-attachments/assets/830a0699-078a-4fa5-8c1c-7abf37b940fa)

![image](https://github.com/user-attachments/assets/d912567e-502c-46bb-b6d4-694d1d705522)

![image](https://github.com/user-attachments/assets/347ad5c6-8dc3-4c23-b932-f4900f616aa9)

The 'Views' dropdown is not working, so can't select the other views

![image](https://github.com/user-attachments/assets/0c8a06ad-861d-4f14-a517-1259b2550efd)

</div>

**Comment by Read2uk** [comment]
On the last screenshot there is a log warning:

LOG.warning: method_exists(): Passing null to parameter https://github.com/Laravel-Backpack/community-forum/issues/2 ($method) of type string is deprecated in C:\localhost\test\vendor\backpack\pro\src\Http\Controllers\Operations\CustomViewOperation.php on line 101

**Comment by jcastroa87** [comment]
Close because is [duplicate](https://github.com/Laravel-Backpack/community-forum/issues/1174)
