### ISSUE TITLE
[Bug] Generating CRUD controller without request still adds request to "use" block

### ISSUE THREAD

**Issue by anxgstadler** [Laravel-Backpack/community-forum#1191]
# Bug report

### What I did

I invoked `php artisan backpack:crud Ensemble` with field validation. The command did not create an `EnsembleRequest` but still added it to the `use` section of the newly created controller:
`use App\Http\Requests\EnsembleRequest;`
This line points to a non existing class.

### What I expected to happen

Omit the line in the controller. When there is no request file being created, it can't be used.

### Is it a bug in the latest version of Backpack?

I'm using the latest version, yes. It was installed only yesterday.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
8.2.22

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, standard, posix, random, readline, Reflection, Phar, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, exif, gd, mysqli, pcntl, pdo_mysql, pdo_pgsql, soap, sockets, sodium, zip, xdebug, Zend OPcache

### LARAVEL VERSION:
11.27.2.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.6
backpack/crud: 6.7.39
backpack/generators: v4.0.6
backpack/theme-tabler: 1.2.13

**Comment by karandatwani92** [comment]
Hey @anxgstadler 

Thanks for pointing this out.

**Comment by pxpm** [comment]
Thanks for the heads up @anxgstadler 🙏 

It's not fixed in `backpack/generators` v4.0.7. A `composer update` should get you the fix. 

Cheers

**Comment by anxgstadler** [comment]
Wow, this was quick!

Great job, thanks! :-)
