### ISSUE TITLE
[Bug] delete users. I get 405 Method not allowed.

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#1204]
Hello Team,

I just received this on email:

"Hello, I have an error when trying to delete users.
I get 405 Method not allowed.
![image-git](https://github.com/user-attachments/assets/2716cb63-fed8-41e9-90d0-c1bb4f916045)
"

**Comment by karandatwani92** [comment]
Hey @backpack-operations 

For the **delete** action, The default HTTP Request type  is `DELETE` as in the screenshot below:

![Screenshot 2024-10-27 at 5 49 04 PM](https://github.com/user-attachments/assets/60ccc6c3-7bfa-4ae6-8e32-103a5d990eea)

Maybe You have some custom code affecting the default behavior, or you have opened the delete link directly in the browser. In your screenshot, I can only see that you are executing a GET request where a DELETE type is expected.

You can check if the `DELETE` request route exists or not in your project by following commands:
```
php artisan route:list --name=user.destroy
php artisan route:list --method=DELETE
```

I hope this helps you to find the problem.
