### ISSUE TITLE
[Bug] with Calendar Operation Buttons month week day not translated

### ISSUE THREAD

**Issue by AndreNeny** [Laravel-Backpack/community-forum#1235]
# Bug report
When the calendar window is displayed, everything is correct, except for the buttons which allow you to change mode between month, week, day are not translated

### What I did
my language : fr
For now, my translations are in the file resources/lang/backpack/calendaroperation.php

### What I expected to happen

Buttons translated. 

### What happened

Text button : backpack.calendaroperation::calendaroperation.month / backpack.calendaroperation::calendaroperation.week ...

### What I've already tried to fix it

In dev, I patched the backpack code in calendar_view.blade.php : buttonText: {
                    today: 'Aujoud\'hui',
                    month: 'Mois',
                    week: 'Semaine',
                    day: 'Jour',
                    list: 'Liste',
                },
!!!

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
Yes
### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
8.2.25

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, json, iconv, SPL, pcntl, random, readline, Reflection, session, standard, mbstring, SimpleXML, sockets, tokenizer, xml, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, i360, imagick, imap, intl, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlwriter, xsl, zip, Zend OPcache

### LARAVEL VERSION:
10.48.22.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.6
backpack/calendar-operation: 1.0.10
backpack/crud: 6.7.41
backpack/devtools: 3.1.7
backpack/editable-columns: 3.0.10
backpack/filemanager: 3.0.9
backpack/generators: v4.0.7
backpack/logmanager: v5.0.2
backpack/menucrud: v4.0.2
backpack/pagemanager: 3.3.2
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.11
backpack/settings: 3.1.1
backpack/theme-coreuiv2: 1.2.6
backpack/theme-tabler: 1.2.15

**Comment by AndreNeny** [comment]
Ouaouh ! Thank's a lot Tabacitu  for this so fast response ! I'll look all of that...

**Comment by pxpm** [comment]
Hey @AndreNeny if you are able to paste here the contents of the translated french file we can add it to the package so that other users can benefit of it.

Here are the english keys that we would need translated to incorporate in the package:
```php
'calendar'      => 'calendar',
    'list-view'     => 'list view',
    'calendar-view' => 'calendar view',

    'update_success' => 'Event updated successfully',
    'update_error'   => 'Failed to update event',
    'delete_success' => 'Event deleted successfully',
    'delete_error'   => 'Failed to delete event',

    'today'   => 'Today',
    'month'   => 'Month',
    'week'    => 'Week',
    'day'     => 'Day',
    'list'    => 'List',
    'all_day' => 'All day',
```

Cheers

**Comment by AndreNeny** [comment]
euh ... Thanks TchatGPT But none of it works.

My translations fr : 

'calendar'      => 'calendrier',
    'list-view'     => 'vue liste',
    'calendar-view' => 'vue calendrier',

    'update_success' => 'Evénement mis à jour',
    'update_error'   => 'Erreur lors de la mise à jour',
    'delete_success' => 'Evénement supprimé',
    'delete_error'   => 'Erreur lors de la suppression',


    'today' => 'Aujourd\'hui',
    'month' => 'Mois',
    'week' => 'Semaine',
    'day' => 'Jour',
    'list' => 'Liste',
    'all_day' => 'un seul jour',

Cheers

**Comment by pxpm** [comment]
Thanks @AndreNeny 🙏 much appreciated. AFAIK point 2 and 3 should work. I will give it some tests to check if there is an issue there when I have time.

I've just released a new version of calendar-operation package including the french translations you provided. Please allow a few moments for our private repository to pick up the changes and you should be able to get 1.0.11 with a `composer update`. 

![image](https://github.com/user-attachments/assets/44e6039c-1acd-4971-8a66-35396ec2b6a2)

Cheers

**Comment by AndreNeny** [comment]
Thank's @pxpm but I have always the same error with calendar Operation 1.0.11, only in prod, buttons Month Week Day are not translated, but List view is translated. See screen copy. 
![2024-11-21_15h02_58 bug #1235](https://github.com/user-attachments/assets/d801c225-ef9d-4c69-aae3-149582f02620)

**Comment by pxpm** [comment]
That's def. because you have two routes with the same name. Backpack register one logout route at https://github.com/Laravel-Backpack/CRUD/blob/13f6fc4f7b5f42361ef78abcf14f6ca8d4ac3461/src/routes/backpack/base.php#L27 but it's called `backpack.auth.logout`. 

I tried to run the same command in some of my backpack applications and it's working as expected, so I assume it's something on your project. 

Maybe if you try `php artisan optimize` on your local dev, you can try to follow the stacktrace and find where those logout routes are defined, even if you need to go into `vendor/laravel/framework` and do some dumps around if you are not using something like `xdebug` that you can use to see the code trace. 

Cheers
