### ISSUE TITLE
[Bug] with Calendar Operation Buttons month week day not translated - See #1235

### ISSUE THREAD

**Issue by AndreNeny** [Laravel-Backpack/community-forum#1237]
# Bug report

### What I did

??

### What I expected to happen

??

### What happened

??

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
replied in previous issue. 👍
