### ISSUE TITLE
[Bug] My Backpack Pro subscription has expired

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#1259]
Hello,

My Backpack Pro subscription has expired, and I am seeking clarification on the following:

If I run composer update, will Laravel and other free packages be upgraded while the paid Backpack packages remain at their current versions?
Could this lead to potential conflicts or instability in my project?
In case of any issues, will I be able to reverse these updates and restore the previous state of my project?

**Comment by pxpm** [comment]
Just to highlight here the appropriate solution is: 
> To avoid potential issues, it's recommended to lock your Backpack packages to the last version you have access to. You can do this by specifying the version in your composer.json file. For example, if the last version of Backpack Pro you had access to was 2.2.4, you should set it as "backpack/pro": "2.2.4" in your composer.json
