### ISSUE TITLE
[Feature Request] Reorder Operations offers no way to use custom-named columns

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#13]
# Bug report

### What I did

Tried to use the Reorder operation on a Model where 
- columns are `parent_id`, `depth`, `left`, `right`
- instead of `parent_id`, `depth`, `lft`, `rgt`

### What I expected to happen

Be able to somehow define the nesting/reordering columns, either in the Model or inside `setupReorderOperation()`

### What happened

There was no way for me to do that, `lft` and `rgt` are hardcoded into the operation.

### What I've already tried to fix it

Nothing - just jotting it down so we don't forget it. We could probably fix this pretty easily:
- [ ] inside `setupReorderDefaults()` we'd look for the `reorder.attributes` setting, if it exists (or was customized using the config file for all CRUDs) then leave it alone; if not set the default ones, something like:
```php
$this->crud->set('reorder.attributes', [
    'parent' => 'parent_id',
    'depth' => 'depth',
    'left' => 'lft',
    'right' => 'rgt',
]);
```
- [ ] use those attribute names everywhere, inside the operation class and operation views, instead of the hardcoded ones;

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
I've added the ability to customize the column names. 

But please, make sure your column names are not sql reserved words, like `LEFT`.
