### ISSUE TITLE
Save actions on edit operation

### ISSUE THREAD

**Issue by aberaldo** [Laravel-Backpack/community-forum#134]
Why if i remove all of the save operations

` $this->crud->removeSaveActions(['save_and_back', 'save_and_edit', 'save_and_new']);`

Backpack crashes??

![image](https://user-images.githubusercontent.com/8792209/162274895-adb396a6-7f12-43b4-9e81-93f29bcd37fc.png)

Why not we can see the edit view without saving button. Something like this:

![image](https://user-images.githubusercontent.com/8792209/162275296-778020d8-581e-4ea1-9e19-496bd573ae55.png)

**Comment by tabacitu** [comment]
Sounds reasonable to me! Thanks @aberaldo !
