### ISSUE TITLE
[Feature Request] Make it easy to add Delete button on Edit page

### ISSUE THREAD

**Issue by WrdVdb** [Laravel-Backpack/community-forum#143]
It happens often I would like to delete a record while on the detail page of a record.
This happens when I know the id of a record, and opening the detail page is easier than looking the record up in the list. Or I have a link to directly to the detail page.

I have made this with a custom resources/views/vendor/backpack/crud/inc/form_save_buttons.blade.blade.php file.

It looks like this:

![image](https://user-images.githubusercontent.com/36230484/168745784-ba183986-2543-4294-b69f-2210dd4daa84.png)

I added a setting:

CRUD::setOperationSetting('showDeleteButton',true);

<pre>
@if(isset($saveAction['active']) && !is_null($saveAction['active']['value']))
    <div id="saveActions" class="form-group">
        <input type="hidden" name="_save_action" value="{{ $saveAction['active']['value'] }}">
        @if(!empty($saveAction['options']))
            <div class="btn-group" role="group">
        @endif
        <button type="submit" class="btn btn-success">
            <span class="la la-save" role="presentation" aria-hidden="true"></span> &nbsp;
            <span data-value="{{ $saveAction['active']['value'] }}">{{ $saveAction['active']['label'] }}</span>
        </button>
        <div class="btn-group" role="group">
            @if(!empty($saveAction['options']))
                <button id="btnGroupDrop1" type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="caret"></span><span class="sr-only">&#x25BC;</span></button>
                <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                    @foreach( $saveAction['options'] as $value => $label)
                    <a class="dropdown-item" href="javascript:void(0);" data-value="{{ $value }}">{{ $label }}</a>
                    @endforeach
                </div>
            @endif
        </div>

        @if(!empty($saveAction['options']))
            </div>
        @endif

        @if(!$crud->hasOperationSetting('showCancelButton') || $crud->getOperationSetting('showCancelButton') == true)
            <a href="{{ $crud->hasAccess('list') ? url($crud->route) : url()->previous() }}" class="btn btn-default"><span class="la la-ban"></span> &nbsp;{{ trans('backpack::crud.cancel') }}</a>
        @endif

        @if($crud->getOperationSetting('showDeleteButton') == true)
            <a href="javascript:void(0)" onclick="deleteEntry(this)" data-route="{{ url($crud->route.'/'.$entry->getKey()) }}" class="btn btn-danger" data-button-type="delete"><i class="la la-trash"></i> {{ trans('backpack::crud.delete') }}</a>
        @endif
    </div>
@endif

{{-- Button Javascript --}}
{{-- - used right away in AJAX operations (ex: List) --}}
{{-- - pushed to the end of the page, after jQuery is loaded, for non-AJAX operations (ex: Show) --}}
@push('after_scripts') @if (request()->ajax()) @endpush @endif
<script>

	if (typeof deleteEntry != 'function') {
	  $("[data-button-type=delete]").unbind('click');

	  function deleteEntry(button) {
		// ask for confirmation before deleting an item
		// e.preventDefault();
		var route = $(button).attr('data-route');

		swal({
		  title: "{!! trans('backpack::base.warning') !!}",
		  text: "{!! trans('backpack::crud.delete_confirm') !!}",
		  icon: "warning",
		  buttons: ["{!! trans('backpack::crud.cancel') !!}", "{!! trans('backpack::crud.delete') !!}"],
		  dangerMode: true,
		}).then((value) => {
			if (value) {
				$.ajax({
			      url: route,
			      type: 'DELETE',
			      success: function(result) {
			          if (result == 1) {
                            document.location.href="{{url($crud->route)}}";
			          } else {
			              // if the result is an array, it means 
			              // we have notification bubbles to show
			          	  if (result instanceof Object) {
			          	  	// trigger one or more bubble notifications 
			          	  	Object.entries(result).forEach(function(entry, index) {
			          	  	  var type = entry[0];
			          	  	  entry[1].forEach(function(message, i) {
					          	  new Noty({
				                    type: type,
				                    text: message
				                  }).show();
			          	  	  });
			          	  	});
			          	  } else {// Show an error alert
				              swal({
				              	title: "{!! trans('backpack::crud.delete_confirmation_not_title') !!}",
	                            text: "{!! trans('backpack::crud.delete_confirmation_not_message') !!}",
				              	icon: "error",
				              	timer: 4000,
				              	buttons: false,
				              });
			          	  }			          	  
			          }
			      },
			      error: function(result) {
			          // Show an alert with the result
			          swal({
		              	title: "{!! trans('backpack::crud.delete_confirmation_not_title') !!}",
                        text: "{!! trans('backpack::crud.delete_confirmation_not_message') !!}",
		              	icon: "error",
		              	timer: 4000,
		              	buttons: false,
		              });
			      }
			  });
			}
		});

      }
	}
</script>
@if (!request()->ajax()) @endpush @endif
</pre>

It would be nice if this is added in backpack. Otherwise updates could be skipped with this file.

**Comment by tabacitu** [comment]
Hmmm... that's interesting. I guess you should be able to easily delete it from the Edit page, since you in the Preview page...

I'm not sure about doing it by default... but we definitely should make it easier to add the delete button there, from the Delete operation... perhaps make it a one-liner. Right now it's difficult to add buttons at the end of the page... we should make it as easy as it is in the ListOperation, using stacks... that way... it _would_ be a one-liner, since the button blade file already exists.

Thanks @WrdVdb , I agree! I'll tag this appropriately and make sure we do it. No promises on _when_ though, we're deep into launching v5.1 with [one very cool but complex feature](https://github.com/Laravel-Backpack/CRUD/pull/4312) 😅

**Comment by pxpm** [comment]
This is already implemented 🫨 

We had it in docs, but not on the operation config file: https://backpackforlaravel.com/docs/6.x/crud-operation-update#delete-button-on-update-operation-1

I've added it to the operation config file.
