### ISSUE TITLE
Assets should be published to public/vendor instead of public/packages

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/community-forum#153]
Recently I ran the free Vite Converter on Laravel Shift, and it modifies a lot of published backpack js assets which it should not do.

I later learn that Laravel Shift ignores the public/vendor folder, I also notice other popular or official laravel packages publish assets to public/vendor (e.g. public/vendor/horizon) too so perhaps we should do the same by publishing to public/vendor/backpack for example. To be consistent with them and also for better compatibility with laravel shift.

**Comment by pxpm** [comment]
We don't have published files anymore. 🤷
