### ISSUE TITLE
[Feature Request] Separate error view pages

### ISSUE THREAD

**Issue by masrodjie** [Laravel-Backpack/community-forum#167]
I think it's good idea for create separate error view pages with main. 

What i've done so far just add in App\Exceptions\Handler.php

```
protected function registerErrorViewPaths()
{
    parent::registerErrorViewPaths();
    if (request()->is('admin/*')) {
        \View::replaceNamespace(
            'errors',
            realpath(base_path('resources/views/vendor/backpack/errors'))
        );
    }
}
```

**Comment by tabacitu** [comment]
I like that! It would be a breaking change, so we can only do this in v6, but if we can do that in a general way, in our ServiceProvider, I'd love it ❤️ The admin panel has its errors views, the app has it's error views... Nice and clean! It's something that's been bothering me for a long _long_ time now, can't wait to finally have it fixed!

Thanks for the solution @masrodjie - any idea if we can do that without making changes to `App\Exceptions\Handler.php`?

**Comment by pxpm** [comment]
They are now separated in Backpack v6. 

Cheers
