### ISSUE TITLE
Upgrade Charts JS Libraries & Chartisan

### ISSUE THREAD

**Issue by promatik** [Laravel-Backpack/community-forum#173]
`Backpack\CRUD\app\Http\ControllersChartController` has quite outdated chart dependencies.
Is 4.2 a good opportunity to update it?

| | current | newest |
| --- | --- | --- |
| Chartjs | `2.7.1` | `3.6.0` |
| Highcharts | `6.0.6` | `9.3.0` |
| Fusioncharts | `3.12.2` | `3.18.0` |
| Echarts | `4.0.2` | `5.2.2` |
| Frappe | `1.1.0` | `1.6.2` |
| D3 | `5.7.0` | `7.1.1` |
| C3 | `0.6.7` | `0.7.20` |

**Comment by tabacitu** [comment]
Since Chartisan v7 has been taken down, and v8 is still not launched (or public anywhere in alpha/beta) we can't do anything about this. What we should probably do in v6.x or later is create ALTERNATIVE chart components and discourage the use of the old `chart` widget.

**Comment by tabacitu** [comment]
This is no longer an option, since Chartisan has been taken down.
