### ISSUE TITLE
[Feature Request] `subcolumns` on `relationship` column, just like we have `subfields` for the `relationship` field

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#184]
# Feature Request

### What's the feature you think Backpack should have?

Now that you're able to add `subfields` to a relationship field, you have a way to create/update that in the Create/Update operation, but no way to show that in the `Preview` operation. 

I haven't thought this through... we need to brainstorm it a little bit. But at first glance, maybe we can do something like:

```php
// hasMany
CRUD::column('items')->type('relationship')->subcolumns(['order', 'description', 'quantity', 'unit_price]);

// hasOne
CRUD::column('passport')->type('relationship')->subcolumns(['number', 'country', 'first_name', 'last_name']);

// etc, where the subcolumn can be 
// - a string  => a text subcolumn
// - an array => the given subcolumn type
```

### Have you already implemented a prototype solution, for your own project?

No

### Do you see this as a core feature or an add-on?

Core

**Comment by cheadevit** [comment]
@tabacitu  Please.

**Comment by tabacitu** [comment]
I believe this is fixed by https://github.com/Laravel-Backpack/PRO/pull/91 - over there we add support for the exact same syntax of the `relationship` field, inside the `relationship` column. So it'll "_just work_".

Let's close this, as it will be done in 2 months when we merge that PR to v6 💪
