### ISSUE TITLE
[5.2.0] Media field type

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#28]
This has been requested a bunch of times - support for [spatie/laravel-medialibrary](https://docs.spatie.be/laravel-medialibrary/v8/introduction/). We never rejected it, but I was always worried about the rate at which Spatie introduce breaking changes. Keeping up-to-date with their packages could become a challenge.

But maybe it will be easier than I first thought, in 4.1, because:
- we can include all the support inside one new field type, ```media```;
- we can deliver that field type as a Backpack add-on - ```backpack/media-field```;

Food for thought. The fact that the package itself can have versioning means we can support newer versions of spatie/laravel-medialibrary without having to bump the Backpack version.

**Comment by Mello21century** [comment]
Any update on this?

**Comment by tabacitu** [comment]
Note to self - take a look at https://github.com/invibe-sk/backpack-on-steroids before creating this field type, looks like they've already done most of the work needed.

**Comment by de-raaf-media** [comment]
Any updates on this? Would be nice if you can open a media window from within summernote / ckeditor field. I think elfinder is overkill for this. And does not look very good on mobile i.m.o.

**Comment by gn0rt0n** [comment]
Really looking for a solution/how-to to get this working.

**Comment by tabacitu** [comment]
@gn0rt0n we're on it. It's the most important item we have for Backpack 5.2, so we'll probably have it launched in early August 2022.

**Comment by tabacitu** [comment]
Notes on how this field could be better than `upload` and `upload_multiple`:

UX:
- [ ] does not show an input, but a dropzone
- [ ] allows drag&drop
- [ ] shows a preview of the uploaded file (or thumnbail of extension)
- [ ] uploads with AJAX
- [ ] shows progress bar (for upload)
- [ ] supports one or more files
- [ ] allows reorders when used for multiple files

DX:
- [ ] one field, not upload and upload_multiple
- [ ] mutator goes away; the Model attribute is ALWAYS the path string; the same thing that is in the DB column;

**Comment by karandatwani92** [comment]
As a backpack user, I'm currently using **browse_multiple** field type to select & reorder media files.
I would love to switch it to this field type, Majorly because it will show attachments preview, and it forces users to upload in a specific directory which helps in organizing files well.

And this migration would be seamless, only if it uses the **same JSON structure**.

**Comment by de-raaf-media** [comment]
UX, maybe:

[] ability to rename a file. 
[] Ability to resize and crop a file?

**Comment by tabacitu** [comment]
I have GREAT news. @jorgetwgroup and @pxpm have been working on this for a few months. We'll soon be launching:
- a new field type called `dropzone`, that will behave as above;
- a new feature called Uploaders, that will allow you to use spatie/laravel-medialibrary super easily;

To make a long story short, the [features above](https://github.com/Laravel-Backpack/community-forum/issues/28#issuecomment-1385050838) will be as easy as:

```php
# step 1
use Backpack\..\DropzoneOperation;

# step 2 
CRUD::field('attachments')->type('dropzone')->withMedia();
```

We're SUPER excited about this. Subscribe to the [blog article digest](https://backpackforlaravel.com/user/newsletters) to be the first one to find out when it's out.

I'll close this issue as we've already incorporated all the feedback here into the features. And have many issues and PRs about it in the closed-source repos. Bad news @de-raaf-media though... we have not added ability to rename, nor resize & crop. Out of scope for this first version. Maybe we'll add them in the future.

Cheers!
