### ISSUE TITLE
[4.1][Feature Request] Simple Array Field

### ISSUE THREAD

**Issue by trip-somers** [Laravel-Backpack/community-forum#34]
I have a need for a field that is similar to 'table' but the stored data is a simple array of scalar values rather than an array of objects. I have googled and read the docs and searched these issues, and I can not find it.

I opened this issue as a potential feature request, but if someone already knows how to do this with what's already included in 4.0, I'd like to be pointed in the right direction.

EDIT: To clarify, the 'table' field will not work for me because the rows do not have field names. Example: ['Value 1', 'Value 2', 'Value 3']

**Comment by tabacitu** [comment]
I think the `table` field covers this use case, with an accessor/mutator. Additionally, in v6 we have [field events](https://backpackforlaravel.com/docs/6.x/crud-operation-create#use-events-in-your-field-definition) so you don't even need to pollute your Model with that logic. So I say let's close this - it's covered. It's not plug-and-play... but it's reasonably easy to do.
