### ISSUE TITLE
[Proposal] Installation - don't overwrite existing error views, when publishing

### ISSUE THREAD

**Issue by ziming** [Laravel-Backpack/community-forum#36]
Currently whenever I do backpack:install it overrides all my existing error pages views

Will be good if backpack error pages (404, 403.etc) stays within backpack routes.

**Comment by ajinzrathod** [comment]
I think there is a hacky way to do this. This will not show the default error page of Laravel but we can hide the description of the Error and I think this looks cooler than the default one.

Open this file **resources/views/errors/layout.blade.php**
```php
@if ($staff_designation == 'admin')  // <- add this line
    <small>
        @yield('description')
    </small>
@endif   // <- add this line
```

To check whether the user is Admin is not, I have used a custom service provider.

**app/Providers/MyServiceProvider.php**
```php
    public function boot()
    {
        view()->composer('*', function($view) {
            $staff_designation = '';
            if (Auth::check()) {
                // write your admin logic here
                $id = auth()->user()->id;
                $staff_designation = auth()->user()->staff_designation;
            }
            return $view->with('staff_designation', $staff_designation);
        });
    }
```

> Remember to edit the Admin Logic

And add the service provider in **config/app.php**
```php
    'providers' => [
         // .....
        App\Providers\MyServiceProvider::class,
   ];
```

In this way, Error Description is viewed only to those who are admin. And all other users just get a 404 page without a Description.

**Comment by pxpm** [comment]
This is already done, we don't overwrite error view anymore for some time 🤷 

This topic slipped, sorry. 

Thanks @ziming 🙏
