### ISSUE TITLE
Are there any plans to for the translation workflow to evolve in Backpack 6?

### ISSUE THREAD

**Issue by pekka** [Laravel-Backpack/community-forum#373]
Currently, the workflow for translating a field value is 

- moving the mouse to the language switcher, clicking, and clicking on the language in the dropdown
- waiting for the page to load
- focusing the field, usually using the mouse
- typing in the translation

<img src="https://user-images.githubusercontent.com/262464/213911855-10573f28-036d-4d7a-b20d-80473c290005.png" width="500">

I'm sure this works fine for many use cases, but when one person is in charge of maintaining two or more languages, it does feel cumbersome:

- It's extra clicks and waiting time
- You have to save whatever other work you may have been doing in the form before switching
- You have no way of seeing the translation in the original language if you're unsure about a nuance and want to compare - but you can't easily switch back either while editing the translation field

(Plus switching the language does not make it the default language when you open the next item! But I suppose that is a separate feature request.)

Are there any plans, perhaps in Backpack 6, to allow for the simultaneous editing of different languages in the same form, something like this:

<img src="https://user-images.githubusercontent.com/262464/213911794-985eac91-c542-4c07-8cd3-ce06e95e0036.jpeg" width="500">

?

Or is someone working on something similar... or perhaps has already done so and I didn't find it in search?

And, thinking further... that kind of layout would make it much easier to integrate a service like Google Translate into the interface!

<img src="https://user-images.githubusercontent.com/262464/213912936-f8f56efb-1260-46a5-8bc3-5f243063f9b2.jpeg" width="500">

**Comment by pxpm** [comment]
Hey @pekka thanks again for the suggestion. 🙏 

There are some plans to improve translations, https://github.com/Laravel-Backpack/CRUD/pull/4267 but they don't go in the direction of having multiple inputs for different languages in the same form. 

I think that's a different UX/UI approach and we don't plan to completely change how it currently behaves (apart from that PR) before v6. 

That PR I mentioned is open for improvements still, so keeping in mind that changing everything is not feasible before v6 launch but improving some stuff there could be doable and we might find a middle term solution here. 

I will be closing this issue, if you have any suggestions regarding translation please write them in that PR thread. 🙏 

Cheers

**Comment by pekka** [comment]
@pxpm ok, fair. 
I may have to do this as a customization down the line, but it'll probably be difficult.
If anything comes out of it that could be turned into an optional add-on, I'll let you know 👍
