### ISSUE TITLE
[Feature Request] SoftDelete / HardDelete operation - allow delete of items that uses SoftDeletes trait

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/community-forum#38]
Hi,
In the case where the model has soft delete enabled, once we delete the entry it puts it to the deleted state.. but there is no way to either restore it? or permanently delete it?

i can only see delete button (again) even on the trashed entries which gives out error as its not actually forcing delete but soft deleting again.

am i the only one have this issue? or is it really not covered in default backpack crud?

**Comment by mgralikowski** [comment]
My vote for filter + replacing the normal _delete_ button with _force delete_ button. I know, we would see this button only when filter is on, but for me, this is ok, clear and safe. Restoring as an option.

**Comment by karandatwani92** [comment]
Feature Request Officially Merged
PR: Laravel-Backpack/PRO#96
Doc: [https://backpackforlaravel.com/docs/5.x/crud-operation-trash](https://backpackforlaravel.com/docs/5.x/crud-operation-trash)
