### ISSUE TITLE
Refresh install of Laravel+Backpack (with recent php & mysql): DevTools not working 

### ISSUE THREAD

**Issue by septen30** [Laravel-Backpack/community-forum#381]
Hi,

I just bought Backpack and DevTools.
My installation is refresh with recent linux/php/mariadb/nginx.

It is not working...

https://flareapp.io/share/qm1K9Rp7#F74
after adding  #[\ReturnTypeWillChange]   to:   public function jsonSerialize()
https://flareapp.io/share/67O0zoa5#F73

![image](https://user-images.githubusercontent.com/124046585/215741405-e835e1a1-b105-403e-bad9-5abffc5bfd7c.png)
![image](https://user-images.githubusercontent.com/124046585/215742217-a9ed2f8f-35e2-46f5-9401-6063297ac98b.png)
![image](https://user-images.githubusercontent.com/124046585/215742743-28d9b55b-2284-4fa5-b8bb-d99a69252236.png)
![image](https://user-images.githubusercontent.com/124046585/215741872-7ad93a82-7841-40a8-acd8-0521457f7c53.png)

**Comment by septen30** [comment]
![image](https://user-images.githubusercontent.com/124046585/215741872-7ad93a82-7841-40a8-acd8-0521457f7c53.png)

**Comment by pxpm** [comment]
Hello @septen30 

I think this issue is the same as https://github.com/Laravel-Backpack/devtools-issues/issues/59 

Can you have a look at my comment at: https://github.com/Laravel-Backpack/devtools-issues/issues/59#issuecomment-1410887339

And also check your server for SQLite installation ? 

Cheers

**Comment by septen30** [comment]
Hello and thank you @pxpm !

There was no recent package of SQLite available on lastest Amazon Linux.
(It will probably be solved in the futur with their upcoming release.)
So I reinstalled a machine with Ubuntu.
It is now working properly.
