### ISSUE TITLE
CKEditor embed in Backpack not working in https environment

### ISSUE THREAD

**Issue by johnowebcoop** [Laravel-Backpack/community-forum#387]
Hi,

I am working with the CKEditor in Backpack, and have encountered an issue where if I try to use the media embed button, I get a popup error when i paste the URL into the modal popup. The error is:

**"Failed to fetch content for the given URL"**

I have seen elsewhere that this may be a http/https issue with the embed function, and when I attempt to test this in a http environment rather than https, it works as expected. I am unsure how to resolve this so that embed works in a https environment (if this is indeed the issue).

Thanks in advance,

**Comment by pxpm** [comment]
Ckeditor has received updates recently, in version 2.2.1 of backpack/pro. 

It now supports elfinder again. 

I am going to close this, I've just tested the embeeding in an https and it worked: 
![image](https://github.com/Laravel-Backpack/community-forum/assets/7188159/29b51c51-bbed-4f43-a7a0-a799d908a832)

Please try a `composer update` and let me know if you are still experiencing issues. 

Cheers
