### ISSUE TITLE
[Bug] License required

### ISSUE THREAD

**Issue by SebTechDevelopment** [Laravel-Backpack/community-forum#393]
# Bug report
The website claims this project is Open-Source and free. But in using the software, you need a license that cost 99,-

### What I did
Set up the project locally, trying to use it for my project.

### What I expected to happen
I expect the panel to be free and open-source, as mentioned on the website.

### What happened
It's not open source and free, as running the panel in production requires a paid license.

### What I've already tried to fix it
Read the EULA

### Is it a bug in the latest version of Backpack?
Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 8.1.15 (cli) (built: Feb  4 2023 19:10:25) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.15, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.12.2@b5b5c635f1a93f277b5248725a1f7ffc97e20810

### BACKPACK PACKAGE VERSIONS:

**Comment by pxpm** [comment]
Closing, please reopen if needed 👍
