### ISSUE TITLE
Using accessor in attribute() causes bug in Search

### ISSUE THREAD

**Issue by CharlieNH** [Laravel-Backpack/community-forum#426]
I wonder if I've stumbled on a sneaky bug ...

The use case is very common: Given a parent table (Supporter) of people, each with a first name and a last name; and given a child table (Subscription) with an FK pointing to the parent table, then the child CRUD needs to show not the actual FK itself but a useful attribute() from the parent instead.

Because the only useful attribute in the parent table is last name _plus_ first name, I created and appended an accessor in the parent model. Here's the accessor code:
```
    protected $appends = [
        'name_last_comma_first'
    ];

    public function getNameLastCommaFirstAttribute() {
        return $this->name_last_1 . ', ' . $this->name_first_1 ;
    }
```
And here's the child CRUD controller code:
```
        CRUD::column('supporter_id_to')    // child column for foreign key to parent
            -> label('To')
            -> type('select')              // the type of Backpack field you want
            -> entity('supporterTo')         // function that defines parent relationship in child Model
            -> attribute('name_last_comma_first')   // column of parent (accessor) shown in Select field
```
That all works brilliantly! The child field/column is indeed a list of last names and first names ... perfect!

BUT when you try to use the Search field on the List page, it crashes as follows:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'supporters.name_last_comma_first' in 'where clause' 
(SQL: select * from `subscriptions` where (exists (select * from `supporters` where `subscriptions`.`supporter_id_from` 
= `supporters`.`id` and `supporters`.`name_last_comma_first` like %dar%) or exists (select * from `supporters` where `subscriptions`.`supporter_id_to` = `supporters`.`id` and `supporters`.`name_last_comma_first` like %dar%) or exists 
(select * from `transactions` where `subscriptions`.`transaction_id` = `transactions`.`id` and `transactions`.`supporter_date_amount` 
like %dar%) or `subscriptions`.`type_subscr` like %dar% or `subscriptions`.`notes` like %dar%) order by `supporter_id_to` asc, 
`id` desc limit 10)
```

It can't find the accessor -- supporters.name_last_comma_first -- when it tries to see if it's `like` the search string. Yet it found the accessor just fine when it displayed it in the List column.

Details:
```
### PHP VERSION 7.4.19
### LARAVEL VERSION v8.83.27
### BACKPACK VERSIONS backpack/crud: 5.4.16; backpack/generators: v3.3.13
```
Is this a bug, or have I done something wrong? Is there a work-around?

Thanks!

**Comment by karandatwani92** [comment]
Hello @CharlieNH,

I tried to mimic the above example by creating a `select` column showing an accessor attribute of parent.
And it was working for me while using search, This may not be a bug or could be something else.

Though i tried this using recent version of backpack "backpack/crud: 5.5.1". i recommend you to update it.

And as a work around you can use [model_function](https://backpackforlaravel.com/docs/5.x/crud-columns#model_function-1) or [closure](https://backpackforlaravel.com/docs/5.x/crud-columns#closure-1) to show concatenated name.

**Comment by CharlieNH** [comment]
Thanks! I updated to 5.5.1, but the symptom is unchanged.

Digging deeper into accessors, I discovered [this](https://laracasts.com/discuss/channels/laravel/how-can-i-query-using-mutator-that-i-defined-in-model), which says that "accessors are only for presentation, not queries." That appears to be entirely consistent with the error message I'm getting, which clearly objects to the presence of my accessor in the query that Search is building.

If I'm right about all that, then the specific instance I'm reporting, in which Search is treating an attribute() as though it were a database column **when the attribute() is actually just a model accessor** would indeed be a bug.

Yet you say it works for you, which is great, so there must be something different about our two bits of code. 

Could you share the accessor code from your parent model and the CRUD::column() from your child controller? Maybe I can learn something that will help me avoid messing up the Search function with my approach.

As a last resort, I will certainly use `model_function` ... thanks! But first I'd like to be sure that Backpack using an accessor in building a Search query really isn't a bug.

Thanks!

**Comment by o15a3d4l11s2** [comment]
Hi @CharlieNH, what you experience is understandable (although maybe not handler gracefully because of the error).
Please refer to https://backpackforlaravel.com/docs/5.x/crud-columns#custom-search-logic-for-columns. This way you can customise your search logic. By the accessor set as attribute, Backpack cannot determine how to do a search, because as you found out accessories are not database columns and therefore cannot be queried.

Here is a proposal solution for your case:
```
CRUD::column('supporter_id')
    ->label('To')
    ->type('select')
    ->entity('supporterTo')
    ->attribute('name_last_comma_first')
    ->searchLogic(function ($query, $column, $searchTerm) {
        $query->orWhereHas('supporter', function ($q) use ($column, $searchTerm) {
            $q->where('name_first_1', 'like', '%' . $searchTerm . '%')
                ->orWhere('name_last_1', 'like', '%' . $searchTerm . '%');
        });
    });
```

Please note that I named my relationship `supporter` instead of `supporterTo

**Comment by CharlieNH** [comment]
This looks like an awesome solution! 

You guys continue to amaze me with the depth of Backpack's capabilities. I'm excited to try this powerful "new" pattern. (New to me, at least.)

Thank you!!

**Comment by karandatwani92** [comment]
Hi @CharlieNH , This is what i did.

Defined accessor in parent model:
```
public function getOwnerNameAttribute(){
  return $this->name;
}
```

Added column in child controller:
`CRUD::column('owner_name_atrr')->type('select')->entity('owner')->attribute('owner_name');`

Defined relation in child model:
```
public function owner(){
  return $this->belongsTo(\App\Models\PetShop\Owner::class, 'owner_id');
}
```

and to make this column searchable go with @o15a3d4l11s2 guide. Thanks @o15a3d4l11s2


**Please close the issue once you get thought with it. Thanks**

**Comment by CharlieNH** [comment]
It works beautifully. Thanks for all your help.

For anyone else who might be struggling to implement a Backpack CRUD for a child table (`Addresses`) whose parent table (`Supporters`) rows can't be clearly identified by the user based on a single parent attribute, here is the complete model I now use for the FK column in the child table. It allows the user to order the child rows by the relevant parent attributes (`name_last` and `name_first`, in this case) _and_ it keeps Backpack from crashing when searching a column whose attribute() is an accessor, not an actual database column.
```
        CRUD::column('supporter_id')    // child column for foreign key to parent
            -> type('select')           // the type of Backpack field you want
            -> entity('supporter')      // function child model that defines parent relationship
            -> attribute('name_last_comma_first')   // column of parent (accessor) shown in Select field
            ->orderable(true)
            // Because attribute(), above, is an accessor in the parent model, 
            //  we MUST include orderLogic() if we want this column to sort properly for the user.
            ->orderLogic(  // Custom logic to make this accessor column sort by parent attributes, not by child FK
                function ($query, $column, $columnDirection) {  // custom query that orders based on attributes underlying the parent accessor
                    return 
                    $query->leftJoin('supporters', 'supporters.id', '=', 'addresses.supporter_id')  // join child to parent
                            ->orderBy('supporters.name_last', $columnDirection)   // order by parent attributes
                            ->orderBy('supporters.name_first', $columnDirection)  // order by parent attributes
                    ;
                }
            )
            // Because attribute() is an accessor in the parent model, 
            //  we MUST include EITHER:
//              ->searchLogic(false)  // the accessor in attribute(), above, will crash Backpack's default Search logic
            // OR include:
            ->searchLogic(  // Custom logic to avoid using the accessor attribute() during Search
                function ($query, $column, $searchTerm) {  // execute a custom query that DOESN'T use the parent accessor
                    $query->orWhereHas('supporter', // parent relationship in child Model
                        function ($q) use ($column, $searchTerm) {  // narrow the parent relationship query based on Search
                            $q->where('name_last', 'like', '%' . $searchTerm . '%')   // examine parent attribute, not accessor
                            ->orWhere('name_first', 'like', '%' . $searchTerm . '%')  // examine parent attribute, not accessor
                            ;
                        }
                    );
                }
            )
        ;
```  
Since this is a very common use case -- ie any app with a "person" table that is parent to any other table -- I hope that future releases of Backpack might implement some or all of this logic in the CRUD:: API.

Again, thanks for all your help with this! I'm really learning to appreciate the depth of functionality that Backpack provides.
