### ISSUE TITLE
[Feature Request] Remove static span elements

### ISSUE THREAD

**Issue by maganius** [Laravel-Backpack/community-forum#433]
# Feature Request

### What's the feature you think Backpack should have?

I think putting static elements around a field limits our possibility to create custom views with the crud.

this example is from relationship it uses select field.

```BLADE
**<span>**
    @if(count($column['value']))
        {{ $column['prefix'] }}
        @foreach($column['value'] as $key => $text)
            @php
                $related_key = $key;
            @endphp

            **<span class="d-inline-flex">**
                @includeWhen(!empty($column['wrapper']), 'crud::columns.inc.wrapper_start')
                    @if($column['escaped'])
                        {{ $text }}
                    @else
                        {!! $text !!}
                    @endif
                @includeWhen(!empty($column['wrapper']), 'crud::columns.inc.wrapper_end')

                @if(!$loop->last), @endif
            **</span>**
        @endforeach
        {{ $column['suffix'] }}
    @else
        {{ $column['default'] ?? '-' }}
    @endif
**</span>**
```
With the wrapper attributes is more than sufficient to any developer can make his custom html.

To create my custom view I need to publish the select column and remove these lines manually, so for the modified field I can't receive any updates on them in the future.

**Comment by maganius** [comment]
Sure, here is...

this is with the modified fields.

![image](https://user-images.githubusercontent.com/8250243/224861089-06e972c8-d893-4bd3-808a-109ee4c03a9c.png)


![image](https://user-images.githubusercontent.com/8250243/224859840-6a5f0676-96b7-4437-98c0-adae63aea602.png)

and this is without the modified fields.

![image](https://user-images.githubusercontent.com/8250243/224860038-ec236d3a-8cb2-4d2d-b80a-362d1908f8c5.png)

![image](https://user-images.githubusercontent.com/8250243/224860086-645f74a5-6bd2-4018-8a26-7d9fba2b63ca.png)

how you can see, i'm not using datatables but using the backpack crud logic, i make my own list.blade view but I want to mantain the fields without modifications to receive future updates on them.

in the previous images the span element is breaking my bootstrap div.

**Comment by tabacitu** [comment]
Hmm... I understand. Sorry @maganius still sounds like you should find a solution in your project - it isn't reasonable for us to remove those `spans`, which are needed in DataTables, to fix your custom view. Those `span`s have a purpose - if you look inside `boolean.blade.php` for example you'll see `<span data-order="{{ $column['value'] }}">` and other places where those spans actually communicate something.

Feel free to _process_ those files if you want, when you load them in your custom view. Or to target them with CSS and make them look any way you want. 

But we can't remove them, sorry - it would break other people's admin panels.

Thank you for understanding.
Cheers!
