### ISSUE TITLE
[WIP] ChatGPT bot to answer people on Github

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#435]
So I've been investigating this for a while now... and some answers are good... some are not so good. But... it does make a lot of progress if you give it feedback... so... I think it does make sense to at least _try it_.

/gpt are you here?

**Comment by tabacitu** [comment]
/gpt what kind of things can I ask of you, as a Github bot? What can you help with?

**Comment by tabacitu** [comment]
Awesome. To interact with you, do I have to use say /gpt every time?

**Comment by tabacitu** [comment]
/gpt that's awesome. To interact with you, do I have to start all my comments with "/gpt"?

**Comment by tabacitu** [comment]
Excellent. Can I do this, though? Can I write a message here that you ignore... but then write another paragraph that you DO NOT?

/gpt can you please tell me the main benefits of using Backpack for Laravel?

**Comment by tabacitu** [comment]
/gpt please tell me - how do you install Backpack v5.5?

**Comment by tabacitu** [comment]
https://www.chatbase.co/ might be able to help. To have one not in Github, but on our website. 

That might be a better idea because it could:
- prevent people from going to Github in the first place
- keep people on our website (or incentivize them to create a Backpack account)

**Comment by tabacitu** [comment]
Just been notified this exists - https://github.com/bhaskatripathi/pdfGPT

**Comment by karandatwani92** [comment]
#### I liked: https://www.chatpdf.com & now they have launched its APIs:
I'll test this after the backpack-v6 launch.
https://www.chatpdf.com/docs/api/backend

![Screenshot 2023-06-28 at 5 35 17 PM](https://github.com/Laravel-Backpack/community-forum/assets/8214221/0a6f5ff2-0ccf-46d5-9dc5-02bd0cdab44b)

**Comment by tabacitu** [comment]
Todo: @karandatwani92 will have a prototype using ChatPDF by the end of the week.

**Comment by tabacitu** [comment]
Update: @karandatwani92 tried using chatpdf:

> I just created a chatbot using chatpdf API. 
> I fed him all the markdown doc. but the answers are silly!!
>
> Sending two chats done on two distinct datasets:
> only the first 100 pages of docs( this was slightly better at answering)
> complete docs

![Screenshot_2023-08-18_at_3 17 10_PM](https://github.com/Laravel-Backpack/community-forum/assets/1032474/82ed8d22-d4c7-40ac-876b-f5a1072f2b6f)
![Screenshot_2023-08-18_at_3 17 34_PM](https://github.com/Laravel-Backpack/community-forum/assets/1032474/a997d973-55c0-4492-9797-8f85e265a668)

**Comment by tabacitu** [comment]
Update: I tried Bing Chat, results were better. So what I take from this experiment... is that the AI you're using... matters. A lot.
<img width="1512" alt="CleanShot 2023-08-18 at 19 43 51@2x" src="https://github.com/Laravel-Backpack/community-forum/assets/1032474/afef2e40-81f0-4c81-a07d-289e2ebdb994">
<img width="1512" alt="CleanShot 2023-08-18 at 19 44 31@2x" src="https://github.com/Laravel-Backpack/community-forum/assets/1032474/afebde95-1609-4aa6-a156-135e7d72c52b">
<img width="1511" alt="CleanShot 2023-08-18 at 19 52 00@2x" src="https://github.com/Laravel-Backpack/community-forum/assets/1032474/b87c8fbc-ec62-4e51-a90b-ab1b8deeee6b">
<img width="1512" alt="CleanShot 2023-08-18 at 19 52 52@2x" src="https://github.com/Laravel-Backpack/community-forum/assets/1032474/a690fc27-7fe8-448a-ac17-4ac8415484a6">
<img width="1512" alt="CleanShot 2023-08-18 at 19 54 11@2x" src="https://github.com/Laravel-Backpack/community-forum/assets/1032474/1c13211d-ca7a-4770-a810-4bdf51e8da5a">

**Comment by tabacitu** [comment]
I also tried ChatGPT 4 with [WebPilot](https://www.webpilot.ai/) addon: https://chat.openai.com/share/5140aa24-587f-4068-b3b7-5e4fa83a3e1f

I think you guys will want to see this.
