### ISSUE TITLE
[Editable Columns][Bug] - reserved word "action" in text field

### ISSUE THREAD

**Issue by ddasios** [Laravel-Backpack/community-forum#456]
Hello there.
I know it is pretty awkward but I found that if you have declared a text column as editable one and you just fill the value: "action" plugin breaks.

**Comment by tabacitu** [comment]
Hi @ddasios ,

I don't quite understand... you can't make a `text` column declared as an editable column, you'd have to change the type of the column from `text` to `editable_text`, right? Can you please provide steps, screenshots or more details, for us to understand what's going on here? We also need to know what "plugin breaks" means... does it throw an error? Which error?

Thanks!

**Comment by ddasios** [comment]
@tabacitu hello!
Yes, I have declared the column as editable_text but content verb "action" seems to be forbidden as a value in the view list. 
As soon as the list operation executes, in the case that one editable_text field exists which has the value ="action", I get an error:

"InvalidArgumentException
Action App\Http\Controllers\{"id":1,"title":"action"} not defined."

So please just try to change an editable_text field on your own to test, just enter value "action".

**Comment by ddasios** [comment]
FYI:
the issue is on file:
vendor/backpack/editable-columns/resources/views/columns/editable_text.blade.php
on line 5
The word "action" makes the `is_callable` php method to return true. Probably there a method called action in this scope.
As a quick fix I have altered the if statement like this:
`if(is_callable($column['value']) && strtolower($column['value']) != 'action') {`

**Comment by ddasios** [comment]
Same issue with word "fake", seems that Faker php package breaks the `is_callable` method again.
So I have excluded in the blade template this word too as the example above. Probably there will be more words that will trigger this issue, so another workaround should be implemented rather than excluding bespoke words as the temporary solution above.

**Comment by o15a3d4l11s2** [comment]
> Same issue with word "fake", seems that Faker php package breaks the `is_callable` method again.
> So I have excluded in the blade template this word too as the example above. Probably there will be more words that will trigger this issue, so another workaround should be implemented rather than excluding bespoke words as the temporary solution above.

You have a natural talent of finding problematic words 😅

**Comment by ddasios** [comment]
@o15a3d4l11s2 haha, not actually. I am working on a project of an online record store website, so word like "fake" or "actton" in record titles are not unusual at all!

**Comment by tabacitu** [comment]
Just tried this again and it's now fixed. Yeey!

![Uploading CleanShot 2024-08-22 at 14.50.06.png…]()

**Comment by ddasios** [comment]
Yes it is fixed on backpack/editable-columns 3.0.5 version.
Thanks a lot!
