### ISSUE TITLE
[Editable Columns][Issue] - global backpack search

### ISSUE THREAD

**Issue by ddasios** [Laravel-Backpack/community-forum#457]
As soon as editable columns plugin is installed, global backpack search (upper right) is not working for the declared editable fields.

**Comment by pxpm** [comment]
Helllo @ddasios 

Thanks for the report 🙏 

We are aware of it, and actually I should have added that to editable columns already but I didn't get to add it until today. 

![image](https://user-images.githubusercontent.com/7188159/228811488-7463059d-a6d5-4a5c-bf27-38772e332032.png)

It's created the PR but not merged yet. 

Do you think it's clear enough for you what need to be done @ddasios ?

Once again thanks for the report 🙏

**Comment by ddasios** [comment]
That is awesome, thanks a lot!
