### ISSUE TITLE
Upload in a relationship with subfield

### ISSUE THREAD

**Issue by miquelangeld** [Laravel-Backpack/community-forum#475]
Hi, I opened the same [issue](https://github.com/Laravel-Backpack/community-forum/issues/406)  which is closed. The [solution](https://github.com/Laravel-Backpack/CRUD/pull/4921) was finally merged? My versions are this:

backpack/crud: 5.5.8
backpack/devtools: 1.3.5
backpack/editable-columns: 2.1.4
backpack/generators: 3.3.16
backpack/langfilemanager: 4.1.0
backpack/pagemanager: 3.0.12
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.4

But still have the same problem I'm unable to upload files from a relationship with subfields and I need it so badly in order to close a project. Thanks in advance guys.

**Comment by pxpm** [comment]
Replied on your other thread @miquelangeld 

Thanks
