### ISSUE TITLE
Malicious link

### ISSUE THREAD

**Issue by MDW-Victor** [Laravel-Backpack/community-forum#483]
In the documentation of https://backpackforlaravel.com/docs/5.x/crud-fields#easymde-pro
The following link of EasyMDE documentation is malicious because he redirect to random unsecure pages
"Show an [EasyMDE - Markdown Editor](https://easy-markdown-editor.tk/) to the user. EasyMDE is a well-maintained fork of SimpleMDE."

**Comment by tabacitu** [comment]
Hmm looks like they didn't pay for their domain name, so somebody else picked it up. Thanks for letting us know, AFAIK the best course of action here would be to replace this link with the one to github - https://github.com/Ionaru/easy-markdown-editor - @jorgetwgroup it's your week, right? You on this?

**Comment by jorgetwgroup** [comment]
Im on it, i will update it.
