### ISSUE TITLE
Datatables responsive toggle as button?

### ISSUE THREAD

**Issue by ceeckhout** [Laravel-Backpack/community-forum#491]
Is there an option to display the datatables responsive toggle as a button on the web pages? So that the user can choose whether or not to display responsively.

Thanks in advance!

**Comment by pxpm** [comment]
Hey there. It is possible sure. 

I think the simplest way it's to have a button, that calls the same list url with a parameter, like: `https://project.com/admin/user?responsive=true`

And in the `setupListOperation` check for the presence of that parameter in the request. Something like:
```php
if (CRUD::getRequest()->has('responsive') { 
    CRUD::setOperationSettings('responsiveTable', true);
}
```
Cheers

**Comment by ceeckhout** [comment]
Thanks a lot @pxpm ! It works. 

Correctly "setOperationSettings" should be "setOperationSetting". Add it in case someone else is looking for the same thing. :-)

**Comment by pxpm** [comment]
Thanks for getting back and for the correction. I corrected my comment, sorry for that, and I am glad you could make it work. 🙏 
Cheers
