### ISSUE TITLE
google_map PRO field

### ISSUE THREAD

**Issue by blondie63** [Laravel-Backpack/community-forum#493]
I'm using this field for a while but from yesterday there some problems on my apps
App retrieve data from location field but can't show map, looking on browser console i see this:
SyntaxError: Unexpected token '�', "�������߅"... is not valid JSON
    at JSON.parse (<anonymous>)
    at bpFieldInitGoogleMapElement (edit:777:49)
    at HTMLInputElement.<anonymous> (edit:966:49)
    at Function.each (bundle.js?v=5.6.0@5316015407af80934be4f66c65176447cce5ef85:2:98234)
    at T.fn.init.each (bundle.js?v=5.6.0@5316015407af80934be4f66c65176447cce5ef85:2:96713)
    at initGoogleAddressAutocomplete (edit:961:48)
    at js?v=3&key=(*my_key*)&libraries=places&callback=initGoogleAddressAutocomplete&language=it:250:146
    at js?v=3&key=(*my_key*)&libraries=places&callback=initGoogleAddressAutocomplete&language=it:249:237

This my config:
### PHP VERSION:
PHP 8.2.5 (cli) (built: Apr 12 2023 11:59:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans
    with Zend OPcache v8.2.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v10.10.1@be0478dea96a6619bb77676f36f67c1500846b17

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.6.0
backpack/devtools: 1.3.5
backpack/editable-columns: 2.1.4
backpack/generators: 3.3.16
backpack/pro: 1.6.4
backpack/settings: 3.0.16

Someone have same problems ?

**Comment by blondie63** [comment]
Error is in resources/views/vendor/backpack/crud/fields/google_map_custom.blade.php around line 175
Maybe Google have changed something in these days :(

**Comment by blondie63** [comment]
@pxpm Have you seen this ? :)

**Comment by tabacitu** [comment]
Hey @blondie63 ,

I just tried both the `google_map` and `google_address` fields and they work ok in my projects:

https://github.com/Laravel-Backpack/community-forum/assets/1032474/079e53c9-1370-45bf-9b62-9878c6bf99d9

But since your error is happening in `resources/views/vendor/backpack/crud/fields/google_map_custom.blade.php`... it looks like it's happening in a custom field, you've created 😀 Not in Backpack's. So it's most likely something you've edited causing this problem.

Cheers!

**Comment by blondie63** [comment]
ok, i've to test better but the problem is saving..

**Comment by blondie63** [comment]
Hi @tabacitu i've done many tests, last using backpack default google_map.blade.php and, i've same error, look:
<img width="1175" alt="BKP_google_map_issue" src="https://github.com/Laravel-Backpack/community-forum/assets/1261851/f8284650-0c5f-4000-9e88-9de6d14fcca1">
The very strange thing is that on my app i've two controller showing same map and getting data from same db record where field values is POINT(11.5439696 45.5496948)
I've created a video to show the issue, as you see, in the first controller the map is displayed correctly and the breakpoint I put on the client side is not intercepted, in the second controller, which has the exact same code related to the CRUD field, the breakpoint intercepts a passage in the line where the variable is evaluated mapField.value which currently contains that strange value. I did the exact same test using the original google_map.blade.php and the problem persists. I really can't figure out the origin! What do you think ?

https://github.com/Laravel-Backpack/community-forum/assets/1261851/12e22773-67e4-497b-8550-aa5ad354548a

**Comment by o15a3d4l11s2** [comment]
Hi, @blondie63, from the video it seems to me that for `MyCompanyCrudController` there is a pre-filled value that you want to edit and for `CompanySitesCrudController` it does not find a value and therefore uses `default_lat` and `default_lng`.

**Please test the following**: in both CRUDs temporarily remove setting the `default_lat` and `default_lng` and test if the problem still exists. I think you just have a non-numeric value there and that's why it breaks.

**Comment by blondie63** [comment]
Hi @o15a3d4l11s2, yes i'm sure that both CRUDs use the exact same database record
How can i test setting "field with some hardcoded" ?

Trying this:
        $this->crud->addField([
            'name' => 'location',
            'label' => trans('backpack::base.site_fields.address'),
            'type' => 'google_map_custom',
            // optionals
            'map_options' => [
                //'default_lat' => $latitude,
                //'default_lng' => $longitude,
                'locate' => true, // when false, only a map is displayed. No value for submition.
                'height' => 400, // in pixels,
                'radius' => $entry->radius, // USO Radius ?? NON penso, refuso di PIC !!
                ],
            'tab' => trans($this->tabLocation)
        ]);
        
        
Have same error

**Comment by o15a3d4l11s2** [comment]
You can do something like
```
$this->crud->addField([
    'name' => 'location',
    'label' => trans('backpack::base.site_fields.address'),
    'type' => 'google_map',
    'value' => '{"lat": 45.5496948,"lng": 11.5439696,"formatted_address": "Contrà Pedemuro, Piazza S. Biagio, 33, 36100 Vicenza VI, Italy"}',
    // optionals
    'map_options' => [
        'default_lat' => $latitude,
        'default_lng' => $longitude,
        'locate' => true, // when false, only a map is displayed. No value for submition.
        'height' => 400, // in pixels,
        'radius' => $entry->radius, // USO Radius ?? NON penso, refuso di PIC !!
    ],
    'tab' => trans($this->tabLocation)
]);
```

**Comment by blondie63** [comment]
Using this you code map is working fine, but how is it possible that in the other controller it works with the original code? As you can see from the screenshot, the two variables $latitude and $longitude are set correctly

<img width="1393" alt="BKP-google_map-debug" src="https://github.com/Laravel-Backpack/community-forum/assets/1261851/75acce39-8874-4c88-93a4-8686972f79ce">

**Comment by o15a3d4l11s2** [comment]
As I wrote in my answer "edit" section - it is most probably corrupted data, as the place that your code breaks from the client-side is where it uses filled-in value and not defaults, so I war initially not right about the problem being the defaults.

**Comment by blondie63** [comment]
Hi @o15a3d4l11s2, In fact, I too think that the problem is related to the data retrieved and sent to the map, but at this point I don't know where to look!
Where does the google_map CRUD get this data?
