### ISSUE TITLE
Devtools Crash

### ISSUE THREAD

**Issue by blondie63** [Laravel-Backpack/community-forum#494]
Adding a simple model DevTools crash and go in loop:

[2023-05-15 18:33:28] local.ERROR: Cannot use Illuminate\Support\Facades\Route as Route because the name is already in use {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Cannot use Illuminate\\Support\\Facades\\Route as Route because the name is already in use at /Users/mauro/Documents/_projects/Laravel/booking-backend/routes/web.php:9)
[stacktrace]
#0 /Users/mauro/Documents/_projects/Laravel/booking-backend/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(243): Symfony\\Component\\ErrorHandler\\Error\\FatalError->__construct(message: ''Cannot use Ill...', code: '0', error: '['type' => 64, ...', traceOffset: '0', traceArgs: '???', trace: '???')
#1 /Users/mauro/Documents/_projects/Laravel/booking-backend/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(230): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->fatalErrorFromPhpError(error: '['type' => 64, ...', traceOffset: '0')
#2 /Users/mauro/Documents/_projects/Laravel/booking-backend/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()
#3 /Users/mauro/Documents/_projects/Laravel/booking-backend/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure:/Users/mauro/Documents/_projects/Laravel/booking-backend/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:253-255}()
#4 /Users/mauro/Documents/_projects/Laravel/booking-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(503): Illuminate\\Routing\\RouteFileRegistrar->register(routes: ''/Users/mauro/D...')
#5 /Users/mauro/Documents/_projects/Laravel/booking-backend/vendor/laravel/framework/src/Illuminate/Routing/Router.php(457): Illuminate\\Routing\\Router->loadRoutes(routes: ''/Users/mauro/D...')
#6 /Users/mauro/Documents/_projects/Laravel/booking-backend/vendor/laravel/framework/src/Illuminate/Routing/RouteRegistrar.php(192): Illuminate\\Routing\\Router->group(attributes: '['middleware' =...', routes: ''/Users/mauro/D...')
#7 /Users/mauro/Documents/_projects/Laravel/booking-backend/app/Providers/RouteServiceProvider.php(37): Illuminate\\Routing\\RouteRegistrar->group(callback: ''/Users/mauro/D...')

My config:
### PHP VERSION:
PHP 8.2.5 (cli) (built: Apr 12 2023 11:59:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans
    with Zend OPcache v8.2.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v10.10.1@be0478dea96a6619bb77676f36f67c1500846b17

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.6.0
backpack/devtools: 1.3.5
backpack/editable-columns: 2.1.4
backpack/generators: 3.3.16
backpack/pro: 1.6.4
backpack/settings: 3.0.16

<img width="759" alt="DevTools-generating-model-issue" src="https://github.com/Laravel-Backpack/community-forum/assets/1261851/21cfe318-243a-42a0-8a33-e0a43b2e2e0e">
[php_errors.log](https://github.com/Laravel-Backpack/community-forum/files/11480125/php_errors.log)

After a composer dump-autoload DevTools generate the model but there are some php errors !
Maybe this info are useful for team :)

**Comment by tabacitu** [comment]
Thanks @blondie63 . Can you please also give me the output of `php artisan backpack:version`? Knowing those versions could help us replicate the issue. Thanks!

**Comment by blondie63** [comment]
@tabacitu i've just posted before image :)

**Comment by blondie63** [comment]
Yes there was a double row: use Illuminate\Support\Facades\Route;
Later i've deleted it and run DevTools again
But I reported the problem to you because it seemed to me excessive behavior, it went in a continuous loop ..
And I've seen other weird errors on php_error.log

**Comment by tabacitu** [comment]
Great! If removing the double-row from your `web.php` file fixed the problem... it means the error was caused by you, not by DevTools, right? AFAIK DevTools does not do `use Illuminate\Support\Facades\Route` in your `web.php` file, it doesn't even touch that file - like Pedro said.

Thanks!

**Comment by blondie63** [comment]
@tabacitu OK
