### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by cgrauls** [Laravel-Backpack/community-forum#497]
Hi,

after a local install of laravel 10.2.1 , backpack 5.6.0, backpack pro , devtools and editable colums in a subfolder . I'm getting 
Uncaught TypeError: Cannot read properties of undefined
when i click on add column when i want to create a model.
url i use is 
http://localhost/Panel/public/admin/devtools/model/create
in chrome devtools i see it wants to load livewire on http://localhost/livewire/livewire.js?id=90730a3b0e7144480175 whih isn't in the correct location. 
![Schermafbeelding 2023-05-22 173107](https://github.com/Laravel-Backpack/community-forum/assets/13330921/4a5f15be-29a1-4964-b9b2-ed56c48306d9)

**Comment by cgrauls** [comment]
same with laravel 9
I found a blog about the livewire. 

C:\wamp64\www\Panel>php artisan livewire:publish --assets

   INFO  Publishing [livewire:assets] assets.

  Copying directory [C:\wamp64\www\Panel\vendor\livewire\livewire\dist] to [C:\wamp64\www\Panel\public\vendor\livewire]  DONE


and copied over the vendor folder to C:\wamp64\www
now a dialog opens when i click on add colum. but its a black window and now the chrome log is saying
index.js:46     POST http://localhost/livewire/message/migration-schema 404 (Not Found)

**Comment by cgrauls** [comment]
![Schermafbeelding 2023-05-22 185806](https://github.com/Laravel-Backpack/community-forum/assets/13330921/915ac91a-02c4-4bdd-a472-aebf97bdafa2)

**Comment by cgrauls** [comment]
so the issue is that livewire can't run if laravel is not in the root. is there a way to bypass this?

**Comment by pxpm** [comment]
Hello @cgrauls I think that's a livewire configuration you need to do when using it in a subfolder. 

I found this https://laravel-livewire.com/docs/2.x/installation#configuring-the-asset-base-url

Let me know if that helps.

Cheers

**Comment by cgrauls** [comment]
> 

thanks that worked :)
