### ISSUE TITLE
Email verification after registration ?

### ISSUE THREAD

**Issue by KevinRignault** [Laravel-Backpack/community-forum#53]
Hi,

Is there a way to send a verification email after registration ?
For now, the user is automatically logged in without verification !

Thank you,
Kevin

**Comment by maurohmartinez** [comment]
Any new on this? It would be awesome to have this! :))

**Comment by sickrandir** [comment]
Hi, I'm also very interested in this. What's the current outlook for this?

**Comment by Cucurrucho** [comment]
please add it

**Comment by AndreNeny** [comment]
+1

**Comment by v-s-public** [comment]
Please add )

**Comment by pxpm** [comment]
Let's close this in favor of https://github.com/Laravel-Backpack/CRUD/pull/5301

This is going to happen before the end of the month 🙏 

Thank you all that vouched for this feature, hope that our solution goes inline with your thoughts. 

Chers
