### ISSUE TITLE
Add custom link when use hint - backpack field

### ISSUE THREAD

**Issue by christmex** [Laravel-Backpack/community-forum#530]
Hi guys, I have some improvement advice for backpack field, please take a look at this form
<img width="454" alt="image" src="https://github.com/Laravel-Backpack/community-forum/assets/34405837/eb1f28a4-9310-496d-822f-42a5556a18dd">

in that picture, I edit the script in developer mode so it's not a real one, my advice is maybe that Would be fantastic if you could provide a link inside the hint? what do you think? is it a good idea? or we shouldn't do that?

Thanks

**Comment by tabacitu** [comment]
Hey @christmex ,

I believe most fields (if not all) have the `hint` attribute non-escaped when it's being outputted: https://github.com/Laravel-Backpack/CRUD/blob/main/src/resources/views/crud/fields/text.blade.php#L20

That means you can already do:

```php
CRUD::field('employment_status')->hint("SIf you don't have one here, please <a target='_blank' href='".backpack_url('status/create')."'>add new</a>");
```

While that's not exactly pretty, is should work... for all fields.

What do you propose we do different?

Cheers!

**Comment by christmex** [comment]
@tabacitu thanks for this, this is exactly what I want to achieve, and I will close this issue, thank you so much. 🙏
