### ISSUE TITLE
Page Expired

### ISSUE THREAD

**Issue by ssimanga** [Laravel-Backpack/community-forum#552]
V6 is giving a 419 page expired error after login and installing devtools
<img width="929" alt="Screenshot 2023-07-04 184155" src="https://github.com/Laravel-Backpack/community-forum/assets/22166547/30ee87c2-4dc3-4b4a-812e-27c67a6d8f8f">

**Comment by pxpm** [comment]
Hello @ssimanga how you doing ?

I can't reproduce your issue, do you mind providing more details ? 

Maybe a `php artisan backpack:version` would help us. 

What are you trying to do when that error happen ? 

When I go to DevTools page everything seems to be working fine. Did you try a `composer update` plus some `php artisan cache:clear` or similar ? 

Cheers

**Comment by ssimanga** [comment]
I ran php artisan cache:clear, still getting the same error message, I can
log in to the dashboard, but whenever I access devtools or any Models I've
creates I'm getting 419 error

[image: image.png]

**Comment by pxpm** [comment]
Do you have any errors in `storage/logs/laravel.log` ? Or any javascript errors in the browser console ? 

It may be an issue with folder permissions and/or session configuration. 

```bash
chmod -R 755 storage

chmod -R 755 vendor

chmod -R 644 bootstrap/caches
```

Do you have your `.env` file properly setup ? Mainly `APP_HOST` ? 

Do you have SQLite extension installed and enabled ? 

What's the output of `php artisan backpack:version` ? 

Sorry I can't help much yet, I need you to give me more details. The error you provide is very general and may have a lot of reasons.

Cheers

**Comment by undefence** [comment]
same problem - with fresh Laravel 10 installation or with upgrading from 8

**Comment by tabacitu** [comment]
@ssimanga a few follow-up questions that might help us reproduce this. Sorry, we're working blind here but we'll do our best:

1. Do you get this error in any other places after you install DevTools, or just the DevTools pages?
2. If you remove DevTools do you still get the problem? I'd try on the Dashboard page but also more importantly on a page with a form - like a CRUD Create/Update operation.

Thanks!

**Comment by pxpm** [comment]
Hey guys @ssimanga @undefence 

I've find that this happens because the `APP_URL` in `.env` file is not correctly set. 

If you are using `php artisan serve` to serve your application in `http://127.0.0.1:8000`, that's what you need to write in `APP_URL`. 

Cheers

**Comment by ssimanga** [comment]
@pxpm, Thanks seems to be working, it was the APP_URL
