### ISSUE TITLE
[Feature Request] Theme switcher

### ISSUE THREAD

**Issue by fronbow** [Laravel-Backpack/community-forum#558]
# Feature Request

### What's the feature you think Backpack should have?

Given the possibility of having more than one theme available, and being able to create our own on the horizon, it would be beneficial for my users to be able to pick themes.
A few of my users are dyslexic so it would be nice to be able to offer them a colour scheme and layout that makes it easier for them to navigate backpack, especially if they could be persisted with their login profile.
Also, my users login on a variety of devices so offering them more display options would be a nice bonus feature (imho).

### Do you see this as a core feature or an add-on?

core or pro add-in

Cheers

**Comment by tabacitu** [comment]
Hey there! Cleaning up old issues. I don't think we should create an official theme-switcher. It's reasonably easy to do (just use the code in our demo). But I would NOT recommend people do this. Offering the admins multiple themes is a recipe for trouble - you would then be maintaining the functionality of both... have the dependency for both etc.

If you need it... fine, do it. But for most projects I think they should refrain from doing that.
