### ISSUE TITLE
Backpack v6 assets path issue

### ISSUE THREAD

**Issue by raviroshanmehta** [Laravel-Backpack/community-forum#575]
I downloaded new Laravel v10 and installed backpack v6. i can see assets urls are wrong in the theme and assets are not loading properly.

In  config/backpack/ui.php i updated the name space - 

`'view_namespace' => 'backpack.theme-tabler::',
 'view_namespace_fallback' => 'backpack.theme-tabler::',`

Below screenshot will be helpful to understand the issue. 

![image](https://github.com/Laravel-Backpack/community-forum/assets/15763132/cfbf8128-b630-4d2b-8de2-e3aecd3cfcd5)

**Comment by raviroshanmehta** [comment]
After facing above issue i reinstalled backpack using `php artisan backpack:install` with default coreui theme. Eveything installed again but assets load issue still exists as referred in below screenshots. 

![image](https://github.com/Laravel-Backpack/community-forum/assets/15763132/748f2524-53cf-4329-8698-ef3b6410d754)

![image](https://github.com/Laravel-Backpack/community-forum/assets/15763132/43e0ff54-b502-42b4-8f13-951b2688ad0f)

**Comment by raviroshanmehta** [comment]
@ctudorache87 any quick work around for this ?

**Comment by tabacitu** [comment]
@raviroshanmehta is it possible you don't have your APP_URL set up correctly in your `.ENV` file?

**Comment by pxpm** [comment]
> @raviroshanmehta is it possible you don't have your APP_URL set up correctly in your `.ENV` file?

This ☝️  or missing permissions to write in the `storage/` folder or missing `php artisan storage:link`

**Comment by raviroshanmehta** [comment]
Issue was with APP_URL. 

Laravel's default APP_URL is [http://localhost](url) . After updating APP_URL to  [http://127.0.0.1:8000](url) everything is working as expected. 

Thanks @tabacitu for saving hours of development efforts of developers for admin development.
