### ISSUE TITLE
Type => 'upload_multiple' Too few arguments error

### ISSUE THREAD

**Issue by Tuoww** [Laravel-Backpack/community-forum#577]
Hi, when using this line of code:
`CRUD::field('photos')->type('upload')->withFiles(['path' => 'productphotos']);`
I can upload 1 image just fine to the productphotos directory.

When trying to change the type to 'upload_multiple' like this: 
`CRUD::field('photos')->type('upload_multiple')->withFiles(['path' => 'productphotos']);`

I am getting the error:
`Too few arguments to function Backpack\CRUD\app\Library\Uploaders\Uploader::getPreviousFiles(), 0 passed in vendor/backpack/crud/src/app/Library/Uploaders/MultipleFiles.php on line 22 and exactly 1 expected`

I've fixed this on my local machine by changing:
`$previousFiles = $this->getPreviousFiles() ?? [];` in vendor/backpack/crud/src/app/Library/Uploaders/MultipleFiles.php
to: 
`$previousFiles = $this->getPreviousFiles($entry) ?? [];`

And this fixes my issue. I hope you guys can add this bugfix in a next version.

Thanks in advance!

**Comment by pxpm** [comment]
Thanks for the report @Tuoww 🙏 

I let that one slip me 😞 fixed in 6.0.6 https://github.com/Laravel-Backpack/CRUD/releases/tag/6.0.6

Cheers

**Comment by tubbynl** [comment]
really nice support guys @pxpm

**Comment by pxpm** [comment]
> really nice support guys @pxpm

Thanks @tubbynl , your kind words are very appreciated 🙏
