### ISSUE TITLE
[4.1][Feature] Pass optional name to uploadFileToDisk

### ISSUE THREAD

**Issue by mserralta** [Laravel-Backpack/community-forum#58]
I think passing an optional extra parameter to set the name of the uploaded file could be nice. If it's ommited md5 function will determine the name as always but if it is passed it will use it.

https://github.com/Laravel-Backpack/CRUD/blob/2fcf8b6e78353118e16899e4e70e46a3ef766f2b/src/CrudTrait.php#L170

**Comment by pxpm** [comment]
We won't be doing this sorry it didn't make it. 

We now have the uploaders, that we are improving even further in the next version. https://backpackforlaravel.com/docs/6.x/crud-uploaders#about
