### ISSUE TITLE
[Bug] Summernote dropdowns don't work in Bootstrap 5

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#581]
Received this report by email:

> In admin panel has a "summernote" field and when the Tabler theme is used, then the buttons with the drop-down menu of this editor cease to work. This is somehow related to this line (48) `@basset('https://unpkg.com/summernote@0.8.20/dist/summernote-bs4.min.js')` in `summernote.blade.php` file. If you replace it with `@basset('https://unpkg.com/summernote@0.8.20/dist/summernote-lite.min.js')` then everything starts to work, but there is a small problem with styles for this editor.
> ![](https://www.fastmailusercontent.com/jmap/download/ue5d940d3/G55f7a295dcb4e7c991c7f9119bc92be7a45f2728/EF8538D5B1A3459C9208FA22DF17FA4A.png?type=image%2Fpng&u=e5d940d3&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzNDJlNTYxNDJmZmMxNDY5Yzc3Mzg5ZmY5MTVkZDY0OSIsInN1YiI6IlJKY2x4NFBBckZZR3RYbmxhWVF6eDd1Wm1ZRkJNNjlubFo5RnBuVmRHXzgiLCJpYXQiOjE2ODk3NjgwMDB9.QLnuwFTD8lI7RuYEam8RranzobvYOfGCIgyNs-H9PgI)

**Comment by tabacitu** [comment]
Just tested this again. I can confirm this is a bug we have, both in CoreUIv4 and Tabler themes. So it's Bootstrap5 related, most likely. It's working in BS4, not working in BS5 🤦‍♂️

**Comment by tabacitu** [comment]
@karandatwani92 any chance you can take a look at this?

**Comment by karandatwani92** [comment]
@tabacitu PR submitted https://github.com/Laravel-Backpack/CRUD/pull/5242

What's left is dark mode support.
