### ISSUE TITLE
[Editable Columns][Bug] - 419 PAGE EXPIRED

### ISSUE THREAD

**Issue by phpMuhammed** [Laravel-Backpack/community-forum#590]
minor-update return 419 exception in staging env.
 knowing that 

1. its work in local env.
2. the staging  env is AWS lambda.

**Comment by pxpm** [comment]
Hey @phpMuhammed did you update your `APP_URL` when moving to prod ?

**Comment by phpMuhammed** [comment]
@pxpm 
yes i do,
knowing that i face the same problem in search request, but i override datatables_logic.blade.php file by adding 
 "headers": {
                    'X-CSRF-TOKEN': '<?php echo e(csrf_token()); ?>'
                },

**Comment by pxpm** [comment]
@phpMuhammed maybe you are missing something. Please check if you have no JS errors in console, and that `common.js` is beeing properly loaded. 

That's where we setup the CSRF token: https://github.com/Laravel-Backpack/CRUD/blob/496b81c96fb426f57ca45e2309e489a0f4303b2d/src/resources/assets/js/common.js#L2

**Comment by phpMuhammed** [comment]
Yes there are errors in the console :
GET https://admin-develop.istoria.app/storage/basset/vendor/backpack/crud/src/resources/assets/css/common.css?37e27744030e net::ERR_ABORTED 404
fan:3359     GET https://admin-develop.istoria.app/storage/basset/vendor/backpack/crud/src/resources/assets/js/common.js?37e27744030e net::ERR_ABORTED 404

and it's looks like in @basset function

**Comment by phpMuhammed** [comment]
[SOLVED]
According to this link https://github.com/Laravel-Backpack/basset#laravel-vapor
I just added these keys to env variables  and its work
BASSET_DISK=s3
BASSET_CACHE_MAP=false
