### ISSUE TITLE
3 issues

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#596]
Received this email today:

> Hi Cristian,
>  
> We recently bought a license for Backpack Pro so that we can use it with Backpack version 6. We were earlier on Backpack version 5.
>  
> I have upgraded the files as per https://backpackforlaravel.com/docs/6.x/upgrade-guide
>  
> I am now getting a 419 error on the List view page. A regular form for new order or new customer opens fine, but the Order list and Customer list screens give a 419 error and don’t show any records. I have tried the following
>  • Changed the application key
>  • Removed the Backpack License key from the .env file to see if Backpack Crud 6.0 itself works fine.
>  
> The following line was not mentioned in base.php at https://github.com/Laravel-Backpack/CRUD/blob/v6/src/config/backpack/base.php put I have added the following line to base.php
>     'license_code' => env('BACKPACK_LICENSE', false),
>  
> No errors are being logged, but the 419 error comes.
>  
> I am also facing two other issues after the upgrade to Backpack version 6
>  
> Problem # 1: When I publish the Backpack Assets, I get the error highlighted below.
>  
> root@ae540874a48e:/var/www/html# php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag=public --force
>  
>    INFO  Publishing [public] assets.  
>  
>    ERROR  Can't locate path: <vendor/backpack/crud/src/public>.  
>  
>  
> Problem # 2: http://localhost/storage/basset/vendor/backpack/crud/src/resources/assets/css/common.css?f87fe3cd3b0b is not found.
> /var/www/html/public/storage points to /var/www/html/storage/app/public
>  
> http://localhost/basset/vendor/backpack/crud/src/resources/assets/css/common.css?f87fe3cd3b0b works fine as this is retrieving the files from the public/basset folder which exists.
>  
> Heartful Regards,
> Sharat

**Comment by pxpm** [comment]
Please @tabacitu tell user to check developer console to make sure `common.js` is being loaded, I guess that's the issue. Again. 

Probably `APP_URL` is not properly set.

**Comment by sharat-rhinofish** [comment]
common.js is not loading and gives a 404 error similar to common.css. The URL shows as http://localhost/storage/basset/vendor/backpack/crud/src/resources/assets/js/common.js?f87fe3cd3b0b and this gives a 404 error. The URL http://localhost/basset/vendor/backpack/crud/src/resources/assets/js/common.js?f87fe3cd3b0b works fine.

The basset folder is at public/basset.

Am I missing some step?

**Comment by sharat-rhinofish** [comment]
All the basset files go into the public/basset folder and not into the storage/app/public/bassets folder as per the documentation. I have tried this with BASSET_DEV_MODE=false and BASSET_DEV_MODE=true in the .env file

**Comment by sharat-rhinofish** [comment]
Hello,

I had to create the vendor/backpack/crud/src/public folder manually. It was not present in the instructions. Once I did that, the php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag=public --force command worked.

I had to symbolically link the storage/app/public/basset folder to public/basset to ensure the Basset files like common.js and common.css were loaded.
This step was not mentioned anywhere.

Please advise if these are missing steps or if I did this incorrectly.

With Regards,
Sharat

**Comment by pxpm** [comment]
Hello @sharat-rhinofish 

You should not need to manually create any folders. 

1 - Can you show me your `config/filesystems.php` ? (at least the `public` disk, if you didn't change basset configuration).
2 - What url do you use in your browser to view your application, and what url is set in `APP_URL` in the `.env` file ? 

Cheers

**Comment by sharat-rhinofish** [comment]
Hi Pedro,

 

#1. Attached is the config/filesystems.php

 

#2. APP_URL entry on my local system is

APP_URL=http://localhost

 

Heartful Regards,

Sharat

 

 

From: Pedro Martins ***@***.***>
Reply to: Laravel-Backpack/community-forum ***@***.***>
Date: Monday, 31 July 2023 at 10:26 PM
To: Laravel-Backpack/community-forum ***@***.***>
Cc: Sharat Hegde ***@***.***>, Mention ***@***.***>
Subject: Re: [Laravel-Backpack/community-forum] 3 issues (Issue #596)

 

Hello @sharat-rhinofish

You should not need to manually create any folders.

1 - Can you show me your config/filesystems.php ? (at least the public disk, if you didn't change basset configuration).
2 - What url do you use in your browser to view your application, and what url is set in APP_URL in the .env file ?

Cheers

**Comment by pxpm** [comment]
Thanks for the reply @sharat-rhinofish 

So, you access your application in browser via `http://localhost/admin/` ? 

Did you ran the `php artisan storage:link` command ?

**Comment by sharat-rhinofish** [comment]
>> So, you access your application in browser via http://localhost/admin/ ?
Yes. The Backpack Dashboard is at http://localhost/admin/dashboard

>> Did you ran the php artisan storage:link command ?
Yes. Within my docker container (which has the root at /var/ww/html), this is what I see:
ls -l public/storage
public/storage -> /var/www/html/storage/app/public

**Comment by pxpm** [comment]
Does this help? https://github.com/Laravel-Backpack/community-forum/discussions/576#discussioncomment-6576557

**Comment by sharat-rhinofish** [comment]
No. I am not seeing a specific resolution for my issue:

With post composer commands, I get the following results. As you can see php artisan basset:fresh deploys the basset files to /public/basset. I am not seeing a basset.php in config folder.

> php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag=public --force

   INFO  Publishing [public] assets.  

  Copying directory [vendor/backpack/crud/src/public] to [public] ................................................................... DONE

> php artisan basset:fresh
Clearing basset '/public/basset'
Done
Looking for bassets under the following directories:
 - resources/views (29 blade files)
 - vendor/backpack/crud/src/resources/views (137 blade files)
 - vendor/backpack/pro/resources/views (97 blade files)
 - vendor/backpack/theme-coreuiv2/resources/views (29 blade files)

Found 210 bassets in 292 blade files. Caching:
 210/210 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

Done in 8.25s
No security vulnerability advisories found

**Comment by pxpm** [comment]
@sharat-rhinofish the solution for that user using Docker was to add the `php artisan storage:link` into their `DockerFile`.

We just released a new basset version that fixed the `fresh` command (it had a bug).

We also added the `basset:check` command that will tell you beforehand if basset is properly configured, if not provide you with some solutions we've been gathering from user experience. 

You can publish the basset config file with: `php artisan vendor:publish --provider="Backpack\Basset\BassetServiceProvider"`

Please update basset to 1.1 then run the `php artisan basset:fresh` again. 

Please don't run `php vendor:publish` on the Backpack assets. We no longer publish any assets. I've also tagged a new CRUD version https://github.com/Laravel-Backpack/CRUD/releases/tag/6.1.2 to remove that command from the package. 

Cheers
