### ISSUE TITLE
On Laravel 10 with Jetstream, Backpack Breaks Navigation Component

### ISSUE THREAD

**Issue by tjarrett** [Laravel-Backpack/community-forum#597]
On a fresh install of Laravel 10 with Jetstream (both 2.x and 3.x) using Livewire and Backpack 6.0 a `Livewire \ Exceptions \ ComponentNotFoundException` is thrown when trying to load the navigation component. The error is:

`Unable to find component: [navigation-menu]`

If I uninstall Backpack, this works fine.

The code from Jetstream that registers the components is in `JetstreamServiceProvider` and looks like this:
```
        $this->app->afterResolving(BladeCompiler::class, function () {
            if (config('jetstream.stack') === 'livewire' && class_exists(Livewire::class)) {
                Livewire::component('navigation-menu', NavigationMenu::class);
                ... 
            }
        });
```

I think what is happening is that Backpack is causing the BladeCompiler to be resolved before Jetstream ever has a chance to register it's callback so that the chunk of code above never fires.

In the [Laravel docs for component namespaces](https://laravel.com/docs/10.x/blade#manually-registering-package-components) they show `Blade::componentNamespace` being called in `boot()` not in `register()` as Backpack 6.0 is doing.

I'd like to propose that Backpack 6.0 move the call to `loadViewComponents` into `boot` instead of `register` **or** doing like Jetstream and wrap the call in an `afterResolving` callback.

I've tried both of those suggestions locally and both solve the problem and Backpack still seems to work just fine -- though I did NOT try all the available themes.

**Comment by pxpm** [comment]
Thanks for the report @tjarrett 

We have other blade directives loaded like you said, and I agree that's the correct way to do it. This one slipped 🔙 

I will create the PR to fix it and let you know 🙏 

Thanks again, cheers

**Comment by pxpm** [comment]
Merged and tagged in https://github.com/Laravel-Backpack/CRUD/releases/tag/6.1.1

Thanks again @tjarrett
