### ISSUE TITLE
Basset files - 404 not found on localhost

### ISSUE THREAD

**Issue by SakshiGrover** [Laravel-Backpack/community-forum#606]
Hi,

I'm seeing 404 not found errors in the console log for the CSS and JS files.
The paths are coming as: http://localhost/var/www/html/vendor/backpack/theme-coreuiv2/resources/assets/css/coreuiv2.css?f87fe3cd3b0b

No errors found on running the command -  php artisan basset:check
Flag BASSET_DEV_MODE=true, added in the .env file
----------------------------------------------------------------------------
Following are the details for the Laravel and Backpack configurations:
### PHP VERSION:
PHP 8.1.21 (cli) (built: Jul  8 2023 07:10:19) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.21, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.21, Copyright (c), by Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans

### LARAVEL VERSION:
10.16.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.1.0
backpack/crud: 6.1.2
backpack/generators: v4.0.2
backpack/permissionmanager: 7.0.0
backpack/pro: 2.0.0
backpack/theme-coreuiv2: 1.1.4

Please advise. 

Thanks

**Comment by pxpm** [comment]
Hello @SakshiGrover 

Can you try the following?
- publish basset config file: `php artisan vendor:publish --provider="Backpack\Basset\BassetServiceProvider"`
- change the basset disk to `basset` instead of the default `public`. 

Ran the `php artisan basset:fresh`. And let me know the results.

Cheers 🙏

**Comment by SakshiGrover** [comment]
Hi Pedro,

Thank you for your quick response.
We tried this solution. It works on Mac but the issue still persists on Windows under Docker.

**Comment by pxpm** [comment]
We have added a `basset:check` command that can help developers pinpoint any errors in asset serving. 

Please run a `composer update` to get the latest version, and then you can run `php artisan basset:check` so Basset will perform a "file cache and serve operation" and report back if it has any issues. 

Let me know if you are still experiencing issues and we can re-open this 🙏 

Cheers
