### ISSUE TITLE
[4.2][Proposal] Should we remove the Clear Filters button?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#62]
Since we now have the "Reset" button, which also clears the search... what point is there in having this button that only clears the filters?

I guess it only makes sense if you disable the "Reset" button, which you can do (globally in the config file or locally in the CrudController), but... who does that? Is there any reason why you'd like to hide the "reset" button?

**Comment by pxpm** [comment]
The main difference I see ATM is that reset button also resets persistent-table status, while filters only clear the filters. 

If you go to the crud page again and persistent is enabled it will trigger the persistent stored in local storage until you 'reset' or the time for persistent expires. 

If I am not wrong this is why both buttons still available. 

Best,
Pedro

**Comment by aberaldo** [comment]
@pxpm @tabacitu i need sth like this. Is there a way to hide the clear filters button? Thanks

**Comment by pxpm** [comment]
If we remove the clear filters, and the user set `showEntryCount => false`, there won't be a way to clear all the filters at the same time. 

This is a no-go IMO. 

@aberaldo you can hide the clear filters button with css. It has the id of `remove_filters_button`: https://github.com/Laravel-Backpack/CRUD/blob/b58f971aa0f0064f5070ae51f90249d9675c2d50/src/resources/views/crud/inc/filters_navbar.blade.php#L23

Closing.
