### ISSUE TITLE
remember_token doesn't work

### ISSUE THREAD

**Issue by smart4you** [Laravel-Backpack/community-forum#629]
Hi,
In the "Login" form, the "name" attribute for the field "Remember Me" is missed. Because of this, $request->filled('remember') will always be FALSE.
![Screenshot 2023-08-10 095302](https://github.com/Laravel-Backpack/community-forum/assets/59228744/fabc2faf-f594-478f-bcc8-2dde5db3715a)
![Screenshot 2023-08-10 095627](https://github.com/Laravel-Backpack/community-forum/assets/59228744/007abd7d-f6ff-40d7-984d-4fa2a5f47948)

**Comment by promatik** [comment]
Hi @smart4you!
Thank you for your report, I just pushed a fix for this one. It will soon be merged 👌

https://github.com/Laravel-Backpack/theme-tabler/pull/135
