### ISSUE TITLE
Widget always getting placed on top

### ISSUE THREAD

**Issue by sharat-rhinofish** [Laravel-Backpack/community-forum#640]
Hello,

My chart widget on Laravel Backpack and the Jumbotron standard Widget are always going to the top of the page, since they are being added to "before_content". How do I ensure that I can add the Chart widget within the content of the page within a specific div?

With Regards,
Sharat

**Comment by tabacitu** [comment]
Hi Sharat,

I'll assume you are using Widgets on a Dashboard or any other custom Backpack page. And that you are defining your widgets in the Controller. If not, please let me know where you're using them.

In Backpack, from the Controller you can [push Widgets to Sections](https://backpackforlaravel.com/docs/6.x/base-widgets#requirements-1). You have the `before_content` and `after_sections`, yes. But you can also create your own custom sections, if you want, to be able to push widgets there from the controller. To create a new widget section your blade file, include this wherever you want the widgets to show up:

```php
@include(backpack_view('inc.widgets'), [ 'widgets' => app('widgets')->where('section', 'name_of_your_custom_section')->toArray() ])
```

And of course replace `name_of_your_custom_section` with your custom name. Then you can push widgets to that section, from your Controller.

Hope it helps.
Cheers!

PS. Let me know if this is what you were looking for. I realise this isn't documented anywhere, and I'm considering adding it.

**Comment by tabacitu** [comment]
Old issue with no reply - closing. Let us know if this isn't solved and we'll reopen!
