### ISSUE TITLE
JavaScript Error and Unresponsive Button After Environment Changes

### ISSUE THREAD

**Issue by kevlongalloway** [Laravel-Backpack/community-forum#645]
After making environment changes (resizing a droplet), I encountered a JavaScript error that is causing a previously functional feature to become unresponsive. The issue seems to be related to cached resources or the environment changes that were made. I have already cleared cache on the laravel application and in the browser. 

**Expected Behavior:**

The "Save" button should trigger the intended action and perform the desired functionality, as it did before the environment changes.

**Observed Behavior:**

The "Save" button does not respond to clicks, and a JavaScript error is encountered in the browser console. The specific error message is: 

`TypeError: form[0].requestSubmit is not a function.`

**Comment by pxpm** [comment]
Hey there @kevlongalloway is that something that happen in all browsers or just in some specific ones ? 

I think we had some issue reported regarding that and it was due to using a very old safari browser. 

Let me know how it goes. 

Cheers

**Comment by tabacitu** [comment]
Hmm that's weird @kevlongalloway . Not sure we can help here, doesn't seem like a bug in Backpack, to be honest. But we'll try our best to help you out. 

Can you also provide a screenshot please? With the Chrome Dev Tools open on Console? Maybe we spot something there that you didn't.

Cheers!

**Comment by tabacitu** [comment]
Closing stale issues. @kevlongalloway if you're still having this please let us know the above and we'll reopen. If you've gotten to the bottom of it, please let us know what was the problem - could help other people who have the same problem.

Cheers!

**Comment by nmalinoski** [comment]
This issue is occurring for me in Pale Moon 33.2.1.
