### ISSUE TITLE
Model Issues in Laravel Version 6

### ISSUE THREAD

**Issue by ainnamran20** [Laravel-Backpack/community-forum#679]
Hello and good day,

I would like to ask a question. I have just opened a new Laravel project with the latest version of Backpack. However, when I open a CRUD controller for the user and try to create a new one also, it shows the error message "CSRF token mismatch," as shown in the picture. Can anyone help me with how to solve this issue? Is it something involve the authentication or other things?

![image](https://github.com/Laravel-Backpack/community-forum/assets/108723258/5dbad602-2741-4c4e-9ba7-82f43f2e63f4)

Thank you

**Comment by pxpm** [comment]
Hey @ainnamran20 

Check in your `.env` file if you have the `APP_URL` properly set including the port number if you are using it to access your project in the browser. 

If that's correct, try a `basset:check` to check if there are any other issues with basset loading. 

Cheers
