### ISSUE TITLE
devtools buttons not working

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#682]
Hello Team,
I just received this on email:
"Hi There,

I just made a fresh install of backpack and devtools and when I click on add model, it'll bring up the module creation page but I cannot add new columns or relations, the button does nothing on click."

**Comment by pxpm** [comment]
Hey @backpack-operations please ask the user to check if there are no errors in the browser console. 

My guess is that the assets are not properly loading, I'd suggest user to try `php artisan basset:check` and if it fails it will give the user some useful options on how to fix it.

Cheers

**Comment by mous13** [comment]
Didn't receive any basset errors. 

I do receive this error in the console on first press

```
create:1969 Uncaught TypeError: Cannot read properties of undefined (reading 'emit')
    at create:1969:29
```

**Comment by mous13** [comment]
Upon further investigation, it seems that the website is trying to load the javascript file "livewire/livewire.js" but cannot find it as its located in "domain.com/dev/public/livewire/livewire.js"

**Comment by mous13** [comment]
Issue Fixed.

Your app is hosted on a non-root path on your domain. For example: https://your-laravel-app.com/application. In this case, the actual assets will be served from /application/livewire/livewire.js, but the generated script tag, will be trying to fetch /livewire/livewire.js.

To solve either of these issues, you can configure the "asset_url" in config/livewire.php to customize what's prepended to the src="" attribute.

For example, after publishing Livewire's config file, here are the settings that would fix the above two issues:

'asset_url' => '/assets'
'asset_url' => '/application'

**Comment by tabacitu** [comment]
Glad you have a solution @mous13 !
