### ISSUE TITLE
delete files bug in AjaxUploader.php

### ISSUE THREAD

**Issue by ivictor777** [Laravel-Backpack/community-forum#687]
Files are not deleted after deletion when I use the dropzone field. I found a bug in the AjaxUploader.php file, the path to the file is incorrect. You need to replace  Storage::disk($this->getDisk())->delete($this->getPath().$value);
 to  Storage::disk($this->getDisk())->delete($value);

<img width="1365" alt="bug" src="https://github.com/Laravel-Backpack/community-forum/assets/15266847/91296de9-290f-4fbe-b487-c5e4a8bfded5">

**Comment by pxpm** [comment]
Hello @ivictor777 

Please make sure you finished the deleting functionality setup described here: https://backpackforlaravel.com/docs/6.x/crud-uploaders#deleting-files-when-entry-is-deleted

Let me know if you still experiencing issues.

Cheers

**Comment by ivictor777** [comment]
@pxpm, This step has been done, but it is responsible for other functionality. Here I am talking about deleting files when I edit an entry where there is a dropzone field and I delete some of the files in it.

**Comment by pxpm** [comment]
Thanks for the clarification @ivictor777 I could confirm your findings.

I've just released backpack/PRO 2.0.13 with this fix, you should be able to get it in a couple hours when our repository is synchronized. 

Thanks again for the report and the time spent here 🙏 

Cheers
