### ISSUE TITLE
EditableColumns Issue

### ISSUE THREAD

**Issue by MartinEntrusit** [Laravel-Backpack/community-forum#740]
There's an issue with the new Tabler theme and the editable columns addon. If we use the editable columns and change some values there, we get new 'Actions' button. Depends on how many times we change something from the editable columns, the same number of new 'Actions' buttons we get.

https://github.com/Laravel-Backpack/community-forum/assets/150701400/d4d2bde9-e2c2-49b1-a5f8-88d0bc2433f0

**Comment by jorgetwgroup** [comment]
Hello @MartinEntrusit i will check about this issue, can yo please share with me some info.

- Where did you config "lineButtonsAsDropdown"?
- Send me the output of `php artisan backpack:version`
- You didn't override any view?

I will be waiting for your answers, thanks.

Cheers.

**Comment by MartinEntrusit** [comment]
> Hello @MartinEntrusit i will check about this issue, can yo please share with me some info.
> 
> * Where did you config "lineButtonsAsDropdown"?
> * Send me the output of `php artisan backpack:version`
> * You didn't override any view?
> 
> I will be waiting for your answers, thanks.
> 
> Cheers.

Hey @jorgetwgroup.

- Backpack:version 
`### LARAVEL VERSION:
10.22.0.0
### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.0
backpack/basset: 1.2.0
backpack/crud: 6.2.0
backpack/editable-columns: 3.0.2
backpack/generators: v4.0.2
backpack/logmanager: v5.0.0
backpack/pagemanager: 3.2.0
backpack/permissionmanager: 7.0.1
backpack/pro: 2.0.11
backpack/settings: 3.1.0
backpack/theme-coreuiv2: 1.2.0
backpack/theme-coreuiv4: 1.1.0
backpack/theme-tabler: 1.1.0`

- "lineButtonsAsDropdown" is configured globally like in the docs "https://backpackforlaravel.com/docs/6.x/crud-operation-list-entries#merging-line-buttons-into-a-dropdown"

- Which views in particular? We do override some of the views but I think they are not related to this issue at all.

Thank you.

**Comment by jorgetwgroup** [comment]
hello @MartinEntrusit i confirm this bug, i will assign it to our patch team, they will handle the fix ASAP.

<img width="1501" alt="Screenshot 2023-11-16 at 08 56 26" src="https://github.com/Laravel-Backpack/community-forum/assets/44643608/aafe819c-3106-406d-97bc-6fdad9f9ae98">

Thanks for open this issue.

Cheers.

**Comment by promatik** [comment]
Hi @MartinEntrusit!
I've added a fix for this at https://github.com/Laravel-Backpack/CRUD/pull/5382 👌

I'll let @pxpm know about this fix, it should be released soon 🙌
Let's move conversation there.
