### ISSUE TITLE
Blank Page error

### ISSUE THREAD

**Issue by ainnamran20** [Laravel-Backpack/community-forum#743]
Hi and good days,

I have an issue that arises when I try to use @extends(backpack_view('noHeaderBlank')), and the page becomes an error. Is there any solution or opinion on this issue? I'm currently using backpack 6.0

![image](https://github.com/Laravel-Backpack/community-forum/assets/108723258/6b485af2-52c2-4ff2-bdaf-719aba81a8f2)

**Comment by jorgetwgroup** [comment]
Hello @ainnamran20 did you have a chance to check about the view?

Thanks.

**Comment by jorgetwgroup** [comment]
Hello @ainnamran20, due to not activity, i will close the issue, in any case, please feel free to re-open or create a new one if needed.

Thanks.
