### ISSUE TITLE
Blank Page error id from #743

### ISSUE THREAD

**Issue by ainnamran20** [Laravel-Backpack/community-forum#746]
Hi and good days,

I have an issue that arises when I try to use @extends(backpack_view('noHeaderBlank')), and the page becomes an error. Is there any solution or opinion on this issue? I'm currently using backpack 6.0

![image](https://github.com/Laravel-Backpack/community-forum/assets/108723258/4825ffd6-a4ca-4593-a97d-7ac930e10153)

This my backpack version and currently i'm using backpack/theme-coreuiv2: 1.2.2
![image](https://github.com/Laravel-Backpack/community-forum/assets/108723258/bf0bd0c5-802a-42c2-8dbb-63e7feed1094)

**Comment by jorgetwgroup** [comment]
Hello @ainnamran20

I think you get this 500 error because the view was not found, are you sure there is a "noHeaderBlank" view, can you show me the file path. Which theme are you using?

And please send me the output of
```
php artisan backpack:version
```

Cheers.

**Comment by ainnamran20** [comment]
hi @jorgetwgroup,

Actually i have provide you the backpack version in my question. Anyway, please refer to the picture attachment below for my backpack version and yes i do use the "noHeaderBlank" view. I'm using backpack/theme-coreuiv2: 1.2.2 theme.

![image](https://github.com/Laravel-Backpack/community-forum/assets/108723258/b831e74f-ef0d-4ff4-8f63-3cf3073461b8)
