### ISSUE TITLE
Backpack not found error 

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#776]
Hello team,

I just received this on email:

"But I got an error when trying to install Backpack Pro on my PC.

like the one below.
PS C:\........\www\backpack-v6> composer require backpack/pro 
./composer.json has been updated
Running composer update backpack/pro
Loading composer repositories with package information 
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev) 
Package operations: 10 installs, 0 updates, 0 removals
 - Downloading backpack/pro (2.0.18)
0/1 (>                ] 0%  Failed to download backpack/pro from dist: The "https://backpackforlaravel.com/satis/download/dist/backpack/pro/backpack-pro-Sabc4134flalaldbfdc435Sbbf6d491a27e6a65-zip-fdd8a2.zip" file could not be downloaded (HTTP/2 40

   Now trying to download from sourc-
 - Syncing backpack/pro (2.0.18) into cache
1/1 [                  100% 
In Git.php line 472:

 Failed to execute git clone --mirror -- https://ghp...A3g:x-oeuth-basic@github.com/Laravel-Backpack/PRO.git C:/Users/...../AppData/Local/Composer/vcs/git-github.cco-Laravel-Backpack-PRO.git/

 Cloning into bare repository 'C:/Users/............
![image001](https://github.com/Laravel-Backpack/community-forum/assets/144793034/66347949-d455-45c8-a4c6-1ffd0a083375)
/AppData/Local/Composer/vcs/git-github.com-Laravel-Backpack-PRD.git'... 
 remote: Repository not found.
 fatal: repository 'https://ghp...A3g:x-oeuth-basic@github.com/Laravel-Backpack/PRD.git/' not found
"

**Comment by karandatwani92** [comment]
Hey @backpack-operations

Please share your composer.json file so that we can find out the issue and help.

Thanks

**Comment by ada27** [comment]
Hi @karandatwani92 

I think that is my case, and can you help me to solve that?

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The skeleton application for the Laravel framework.",
    "keywords": ["laravel", "framework"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "backpack/crud": "^6.3",
        "backpack/editable-columns": "*",
        "backpack/permissionmanager": "*",
        "backpack/pro": "*",
        "backpack/theme-coreuiv4": "^1.1",
        "backpack/theme-tabler": "*",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.3",
        "laravel/tinker": "^2.8"
    },
    "require-dev": {
        "backpack/devtools": "*",
        "backpack/generators": "^4.0",
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "post-install-cmd": ["php artisan storage:link --quiet"]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.backpackforlaravel.com/"
        }
    ]
}

**Comment by karandatwani92** [comment]
```
"backpack/crud": "^6.4",
"backpack/editable-columns": "^3.0",
"backpack/permissionmanager": "^7.0",
"backpack/pro": "^2.0",
"backpack/theme-coreuiv4": "^1.1",
"backpack/theme-tabler": "^1.0",
```
I used your `composer.json` with the above. It Worked!

**Comment by ada27** [comment]
Hi @karandatwani92,

I can't access that link, as you mentioned. 
![image](https://github.com/Laravel-Backpack/community-forum/assets/44355293/e04560d1-8584-4fb2-a871-baf315279d84)

I tried again, but I got an error like the picture below.
![Screenshot 2023-12-06 083946](https://github.com/Laravel-Backpack/community-forum/assets/44355293/dbff8ae3-acde-477a-98fb-51d606360feb)

I already bought a backpack everything, but I read on the log that I couldn't find any repositories.

**Comment by karandatwani92** [comment]
Try this https://backpackforlaravel.com/user/tokens

Go to the instructions tab, and follow the instructions.

**Comment by pxpm** [comment]
@ada27 also try to clear composer caches with: `composer clear-cache` and make sure you are not overwriting the default composer behavior, because it seems that's trying to get the `backpack/pro` from the github repository, when it should be getting it from the private repo (as you don't have access the the github repository). 

Also I noticed from the composer.json you posted that you have some packages without specified version(like `backpack/pro: ""`). @karandatwani92 provided a list of compatible version numbers, so you can fill up those missing package versions and try to install again. 
If you are still having issues let us know.

Cheers

**Comment by ada27** [comment]
Thanks, @karandatwani92 and @pxpm, for your advice.
I added the auth.json credential to my project, and I can access repositories clearly.

Can I delete auth.json and backpack license on env before I deploy a project on the client server?
because my credentials clearly show up in auth.json.

**Comment by karandatwani92** [comment]
Hey @ada27 

You need credentials on client-server too!
Ask your client to create a backpack account & get you a license from their account.
