### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#781]
Hello Team,
I just received this email but I can`t find it in the documentation.

"I am interested in buying BackPack and I have a question about language support and how to enable right-to-left (RTL) in my application.

Is RTL supported?

Thanks"

**Comment by promatik** [comment]
Hi!

RTL is supported, it must be configured at: 

`\config\backpack\ui.php`

```php
'html_direction' => 'rtl',
```

Regarding language support, backpack also supports multi language. It is currently translated in 36 locales.

**Comment by pxpm** [comment]
This is probably solved by now. 

Thanks @promatik 

@backpack-operations re-open if needed. 🙏
