### ISSUE TITLE
fix typo in url at docs/crud-fields table field

### ISSUE THREAD

**Issue by nikkyandrei** [Laravel-Backpack/community-forum#788]
in backpack/docs/crud-fields at the field "table" there is a link on the  "attribute casting" words at : 
`It's highly recommended that you use [attribute casting]`

To fix this in all version replace link from :
https://mattstauffer.co/blog/laravel-5.0-eloquent-attribute-casting
to :
https://mattstauffer.com/blog/laravel-5.0-eloquent-attribute-casting
exception v3.6 where the is link :
https://laravel.com/docs/eloquent-mutators#attribute-casting

Suggestion: use same link in all versions maybe ?

**Comment by jorgetwgroup** [comment]
Hi @nikkyandrei thanks for the catch i add a PR fixing this problem will be merged ASAP.

Cheers.
