### ISSUE TITLE
[Feature Request] link() helper on CrudColumn and certain CrudFields

### ISSUE THREAD

**Issue by selected-pixel-jameson** [Laravel-Backpack/community-forum#8]
# Feature Request

### What's the feature you think Backpack should have?

Backpack just implemented the relationship option for ajax selects and multiple selects. It would be nice to have a property in these select fields along the lines of 'hyperlink => true', which would make the items that are listed out clickable and would allow the user to navigate to that specific model's CRUD Controller to edit / view that item by clicking on it. 

Right now our clients ask for this all the time and we end up building out custom templates for this which is a lot of work and renders a large feature of backpack pretty useless for us because of a smaller requirement. 

### Have you already implemented a prototype solution, for your own project?
No

### Do you see this as a core feature or an add-on?

Core Feature

**Comment by tabacitu** [comment]
@karandatwani92 let's do a prototype for:
```php
CRUD::column('category')->linkTo('category.show'); // note that this is the ROUTE NAME, not OPERATION NAME
```

We might also add a helper (macro) for ease of use:

 `CRUD::column('category')->linkToShow();` that points to `route('monster.show', $id)` if that route exists.

But not in the prototype.

**Comment by karandatwani92** [comment]
PR https://github.com/Laravel-Backpack/CRUD/pull/5317

**Comment by pxpm** [comment]
3 years later and we got it. 🙏 🥳 
PR: https://github.com/Laravel-Backpack/CRUD/pull/5317
DOCS: https://github.com/Laravel-Backpack/docs/pull/519

Reviewed. will be released in the next couple hours. We can safely close this, it's on next Backpack version: 6.2.5
