### ISSUE TITLE
[Bug] Error 500 due to Uploaders

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#801]
# Bug report

### What I did

A user tried our demo, in our Product CRUD they tried to edit a product:

https://demo.backpackforlaravel.com/admin/product/210/edit

### What I expected to happen

Edit form to open. 

### What happened

Error 500: `Backpack\CRUD\app\Library\Uploaders\Support\RegisterUploadEvents::handle(): Argument #2 ($uploaderConfiguration) must be of type array, bool given, called in /home/forge/demo.backpackforlaravel.com/vendor/backpack/medialibrary-uploaders/src/AddonServiceProvider.php on line 40`

<img width="1496" alt="CleanShot 2024-01-16 at 10 54 23@2x" src="https://github.com/Laravel-Backpack/community-forum/assets/1032474/7629a400-b07d-4098-a73f-0847f23c4c3c">

### What I've already tried to fix it

Nada... @pxpm ?

**Comment by karandatwani92** [comment]
I remember this error was fixed.
I suspect it is happening because our demo has not been updated from past 2 months.

`composer update` may help there.

**Comment by pxpm** [comment]
Thanks @tabacitu didn't noticed it, it was indeed lacking to run `composer update` as I've just did.
