### ISSUE TITLE
[Bug] Slug field doesn't properly slug German characters

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#802]
# Bug report

### What I did

A user reported this by email, that in our Monster demo:
![german](https://github.com/Laravel-Backpack/community-forum/assets/1032474/af968229-c5d1-45f9-b4b5-b782fb8ee3ff)

### What I expected to happen

They expected the following characters to be converted like this:

```
Ü => UE
Ä => AE
Ö => OE
ü => ue
ä => ae
ö => oe
ß => ss
```

### What happened

Not the above.

### What I've already tried to fix it

Nothing.

**Comment by pxpm** [comment]
Hey Cristian, thanks for the report.

If you have verified the "bug" and it requires patch team intervention to degub/fix/answer please make the correct assignments, no need to "retriage" I think.🙏 

@karandatwani92 ChatGPT got it totally wrong here. I've already created the PR where it actually works: 

![image](https://github.com/Laravel-Backpack/community-forum/assets/7188159/6d7ce58e-1d60-4c73-b20b-0591800cd620)

But decided to give a test in your proposed solution, and as I expected, **it does not work**. 

![image](https://github.com/Laravel-Backpack/community-forum/assets/7188159/e5a6c96f-4781-4675-be9c-747ad7271cd3)

Some of those characters are called German Umlats (I didn't know, just found out now: https://www.studying-in-germany.org/learn-german/german-umlauts)

What I mean here, those comments add confusion to the problem, as they do not really solve the problem. I have nothing against using ChatGPT, I use it myself. But I would take care to test if the "guy" is giving me the correct instructions or not. 

Here is the PR: https://github.com/Laravel-Backpack/PRO/pull/223

**Comment by tabacitu** [comment]
Fixing in https://github.com/Laravel-Backpack/PRO/pull/223
