### ISSUE TITLE
[Bug]  Bulk restore not working

### ISSUE THREAD

**Issue by mariusconstantin2503** [Laravel-Backpack/community-forum#817]
# Bug report

### What I did

I enabled the trash operation adding the soft deletes on the model and the trait in the crud, as it is specified in the documentation. The trash and bulk trash are working but bulk restore not. I received an error "Call to undefined method Illuminate\Database\Eloquent\Builder::onlyTrashed()"
It seems to come from here
![image](https://github.com/Laravel-Backpack/community-forum/assets/4282568/d8a8e03d-bf0d-45c2-b30b-facbfaf621d3)

### What I expected to happen

To successfully restore the items 

### What happened

An exception is shown

### What I've already tried to fix it

yes

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?
yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
![image](https://github.com/Laravel-Backpack/community-forum/assets/4282568/ed3fc3fa-cad5-416e-ad65-4ef1abcac4c1)

**Comment by karandatwani92** [comment]
Hey @mariusconstantin2503

I checked our demo, It's working there.
https://demo.backpackforlaravel.com/admin/pet-shop/pet

Please share your CRUD controller to identify the issue & help.🤝

**Comment by pxpm** [comment]
It's probably missing to add `SoftDeletes` trait to the model. Also make sure you have the soft delete column in your database.

**Comment by tabacitu** [comment]
> It's probably missing to add `SoftDeletes` trait to the model. Also make sure you have the soft delete column in your database.

Yup, sounds like that should be the problem.
