### ISSUE TITLE
Dev Tools - Getting Maximum execution time of 30 seconds exceeded error after upgrade to vr. 3.0.4

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#833]
### Discussed in https://github.com/Laravel-Backpack/community-forum/discussions/831

<div type='discussions-op-text'>

<sup>Originally posted by **webteamseo** February  6, 2024</sup>
Hi,
here is the info:
https://flareapp.io/share/W7zwOY25

When I try to change the max_execution_time to 120 it still doesn't work.

I've also removed all paths from config/devtools.php.

If I downgrade to version 2.0.X it works, but not usable (buttons are misplaced and checkboxes cannot be checked).

I am on Laravel 10.43 - recently upgraded
Backpack 6 - recently upgraded
Devtools 3.0.4
PHP 8.2.1
Macbook pro with Homestead Laravel with VM with 4 cpu's and 8 GB Memory allocated.

Any help would be really appriciated.   </div>

**Comment by jcastroa87** [comment]
Close because duplicate [issue](https://github.com/Laravel-Backpack/community-forum/discussions/831)
