### ISSUE TITLE
[Bug] Display avatar image

### ISSUE THREAD

**Issue by tringuyenduc2903** [Laravel-Backpack/community-forum#849]
# Bug report

### What I did
File **config/backpack/theme-tabler.php** 
```'layout' => 'vertical_dark',```

### What I expected to happen
Two avatar images are shown
**Mobile**
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/87686cfd-7646-4e27-9b02-da1d090f2b04)

**Computer**
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/0f95e563-b468-45c8-b4d0-f0b67e8f198c)

### What happened
The avatar image is at the 2nd display position (in Phone) and shows the Computer error frame
**Mobile**
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/aae8288a-5edf-46b2-9c39-3e30f0542f00)

**Computer**
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/ac3d6ce6-06b3-4413-b1c0-964ee370fd51)

![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/8996f81a-03d6-4108-8874-a13259ebb15c)

### What I've already tried to fix it
Remove ```, 'LOADED'``` in  **vendor/backpack/crud/src/helpers.php**
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/e3b67e15-3723-4f8f-9c62-fdbc2af4cba0)

### Is it a bug in the latest version of Backpack?

After I run ```backpack composer update backpack/crud``` the error it still persists

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/63312b7d-df4f-460b-aa5a-0444690045a6)

**Comment by karandatwani92** [comment]
Hey @tringuyenduc2903 

We have a PR open at: https://github.com/Laravel-Backpack/theme-tabler/pull/159 to fix the menu/navbar. I've listed your reported issue there.

You can follow the progress there, will be closing this one for now. 

Cheers
