### ISSUE TITLE
[FEATURE] Allow change request method in select2_ajax filter to work with FetchOperation

### ISSUE THREAD

**Issue by mahasadhu** [Laravel-Backpack/community-forum#85]
# Bug report

### What I did

Creating a `select2_ajax` filter with fetch using these codes:
```
        CRUD::filter('place_category')
            ->type('select2_ajax')
            ->label(trans('backpack::base.place_category'))
            ->placeholder(trans('backpack::base.choose_place_category'))
            ->values(backpack_url('place/fetch/place_category'))
            ->whenActive(function ($value) {
                $this->crud->addClause('where', 'place_category_id', $value);
            })
            ->apply();
```

Fetch method:
```
    protected function fetchPlace_category()
    {
        return $this->fetch([
            'model' => \App\Models\Place_category::class, // required
            'searchable_attributes' => ['name'],
            'paginate' => 10, // items to show per page
        ]);
    }
```
### What I expected to happen

Filter works out fine

### What happened

Backpack return this error
![image](https://user-images.githubusercontent.com/13914485/95754467-a8883c00-0cd5-11eb-98dd-5c61a2357200.png)

### What I've already tried to fix it

Add `->method("POST")` to the fluent syntax factory, but still not working like in `field` method.
```
        CRUD::filter('place_category')
            ->type('select2_ajax')
            ->label(trans('backpack::base.place_category'))
            ->placeholder(trans('backpack::base.choose_place_category'))
            ->values(backpack_url('place/fetch/place_category'))
            ->whenActive(function ($value) {
                $this->crud->addClause('where', 'place_category_id', $value);
            })
            ->method("POST")  // <-- NOT WORKING
            ->apply();
```

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
### PHP VERSION:
PHP 7.4.5 (cli) (built: Apr 14 2020 16:17:34) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.8.0@0bdd5c6f12cb7cb6644e484169656245af417735

### BACKPACK VERSION:
4.1.25@23fb1ed5153d5465d49d2fe1ca265a5985c78877

**Comment by tabacitu** [comment]
I agree! That's what's intuitive. 

Moved to Ideas and tagged for 4.2.0 since we're currently in a feature freeze in 4.1.x - we're just fixing all the bugs we can without a breaking change. Then we'll start bringing new features into 4.2.0.

**Comment by pxpm** [comment]
This is done: https://backpackforlaravel.com/docs/6.x/crud-operation-fetch#using-fetchoperation-with-select2_ajax-filter
