### ISSUE TITLE
[Bug] Cancel button interface error

### ISSUE THREAD

**Issue by tringuyenduc2903** [Laravel-Backpack/community-forum#850]
# Bug report

### What I did
Check the theme (**Dark Theme**)

### What I expected to happen
The Cancel button displays the Label
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/2b7b0cfd-539f-4304-9026-d3d92ab48727)

### What happened
The Cancel button does not display the Label
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/31440f7a-c83f-4548-b7e3-4335eed1ed91)

### What I've already tried to fix it
Overwrite Scss file with Vite
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/57d3e329-cf38-429b-9d12-9c6ab0b9745f)

### Is it a bug in the latest version of Backpack?

After I run ```backpack composer update backpack/crud``` the error it still persists

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/a5a3d9dd-0ef3-4a5e-b9ad-ebe47327102d)

**Comment by karandatwani92** [comment]
Hey @tringuyenduc2903

Thanks for reporting the issues with the theme and sorry for the inconvenience.

I have created a single issue [here](https://github.com/Laravel-Backpack/theme-tabler/issues/160) to list all dark mode-related issues in one place.
You can follow the progress there, will be closing this one for now.
