### ISSUE TITLE
[Bug] Error displayed for select, select2,...

### ISSUE THREAD

**Issue by tringuyenduc2903** [Laravel-Backpack/community-forum#851]
# Bug report

### What I did
Check the interface for fields **select, select2,...**

### What I expected to happen
The **Selected options** can still be seen, but in a lighter color similar to the **Light theme**
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/d79fbe63-ed95-4ed8-aef8-0bb1a8bd434e)

### What happened
The **Selected option** cannot be seen if the mouse is hovered over **Another option**
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/20922ca2-cd68-415f-9eed-33e0518189d3)

### What I've already tried to fix it
The problem lies in the **Css**, find them!

### Is it a bug in the latest version of Backpack?

After I run ```backpack composer update backpack/crud``` the error it still persists

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/c5c5d1ea-fc2b-4816-8768-73f4e6f0e880)

**Comment by karandatwani92** [comment]
Hey @tringuyenduc2903 

Thanks for reporting the issues with the theme and sorry for the inconvenience.

I have created a single issue [here](https://github.com/Laravel-Backpack/theme-tabler/issues/160) to list all dark mode-related issues in one place.
You can follow the progress there, will be closing this one for now.
