### ISSUE TITLE
[Bug] Can't see what you're typing (Dark theme, Filter feature, Select2 type)

### ISSUE THREAD

**Issue by tringuyenduc2903** [Laravel-Backpack/community-forum#852]
# Bug report

### What I did
Check the **Dark theme**, **Filter feature**, **Select2 type**

### What I expected to happen
The text inside the Input box is visible as a **Light theme**
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/12c0cf20-a2de-4a9a-9654-8e446bca373f)

### What happened
Can't see what you're typing
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/20db4f7e-85cf-472b-905e-81e33cf7d02c)

### What I've already tried to fix it
The problem lies in the **Css**, find them!

### Is it a bug in the latest version of Backpack?

After I run ```backpack composer update backpack/crud``` the error it still persists

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/6b2555e1-1018-44e4-9f0b-fcb963a7b027)

**Comment by karandatwani92** [comment]
Hey @tringuyenduc2903 

Thanks for reporting the issues with the theme and sorry for the inconvenience.

I have created a single issue [here](https://github.com/Laravel-Backpack/theme-tabler/issues/160) to list all dark mode-related issues in one place.
You can follow the progress there, will be closing this one for now.
