### ISSUE TITLE
[Bug] Loss of user management support area

### ISSUE THREAD

**Issue by tringuyenduc2903** [Laravel-Backpack/community-forum#854]
# Bug report

### What I did
Log out the user

### What I expected to happen
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/e7adde6b-8395-4bc4-b7a8-6f873ed92ada)
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/1f848234-11b6-46b7-a64e-421e09453438)

Found the logout button in theme [theme-tabler](https://github.com/Laravel-Backpack/theme-tabler) **vertical, vertical_dark, right_vertical, right_vertical_dark, right_vertical_transparent**

### What happened
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/bc27aff3-d69e-4399-b76e-e702b1e79763)

Loss of user management support area

### What I've already tried to fix it
This error occurred in the recent ```composer update```. FInd them!
https://github.com/Laravel-Backpack/theme-tabler/commit/fd98511a702fd7216710d035d7ff0f6c90d76193

### Is it a bug in the latest version of Backpack?
After I run backpack ```composer update backpack/crud``` the error it still persists

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/42dd570e-2bfe-4ccf-a98b-516800223671)

**Comment by pxpm** [comment]
it's fixed, a composer update should get the menu back. 
Sorry @tringuyenduc2903 🙏
