### ISSUE TITLE
Broken link on our website

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#857]
Hello team,

A broken link on our website just has been reported on this page https://backpackforlaravel.com/docs/6.x/base-widgets#chart-pro at step 4
![image](https://github.com/Laravel-Backpack/community-forum/assets/144793034/431200b7-aca6-448c-ad86-aff03684de6b)

Please fix it, Thank you!

**Comment by jcastroa87** [comment]
Hello @backpack-operations im on it.

Thanks.

**Comment by jcastroa87** [comment]
I create t[his PR](https://github.com/Laravel-Backpack/docs/pull/555) to fix this issue.

Cheers.
