### ISSUE TITLE
How to edit trashed (soft deleted) item

### ISSUE THREAD

**Issue by msyadav88** [Laravel-Backpack/community-forum#867]
### Discussed in https://github.com/Laravel-Backpack/community-forum/discussions/866

<div type='discussions-op-text'>

<sup>Originally posted by **msyadav88** March  3, 2024</sup>
I want to edit a trashed item which is soft deleted, but it is giving 404 error. 
The url is like /admin/orders/7/edit 
Also the show page giving 404 /admin/orders/7/show</div>

**Comment by jcastroa87** [comment]
Closes as [duplicated](https://github.com/Laravel-Backpack/community-forum/discussions/866).
