### ISSUE TITLE
CRUD: currency columun

### ISSUE THREAD

**Issue by blondie63** [Laravel-Backpack/community-forum#875]
### Discussed in https://github.com/Laravel-Backpack/community-forum/discussions/873

<div type='discussions-op-text'>

<sup>Originally posted by **blondie63** March 10, 2024</sup>
How can i set a column to show a currency fields with correct format for Italy ?
<img width="1205" alt="BKP6 x-currency" src="https://github.com/Laravel-Backpack/community-forum/assets/1261851/aa739817-174e-4693-adf9-880a7ff05fc6">

i'm using BackPack v6

Thanks for help :)</div>

**Comment by blondie63** [comment]
https://github.com/Laravel-Backpack/community-forum/discussions/873#discussioncomment-8741888

**Comment by karandatwani92** [comment]
Hey @blondie63
I'll check it. I think we should continue the discussion over there.
I'm closing this one & reopening the [previous thread](https://github.com/Laravel-Backpack/community-forum/discussions/873) to keep everything in one place.
