### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ricoroma-coder** [Laravel-Backpack/community-forum#883]
# Bug report

### What I did

I just installed Backpack 6.7 in a project with Laradock.

Created a simple CRUD from Users, with all default options, but when I try to access any route, this modal shows:

![image](https://github.com/Laravel-Backpack/community-forum/assets/64080305/2c98c06b-ef0b-4350-8001-6eaad5bd71ca)

That's my .env file:

![image](https://github.com/Laravel-Backpack/community-forum/assets/64080305/559a2c27-2141-407e-91ee-271769fe2c13)

### What I expected to happen

Without docker, it works:

![image](https://github.com/Laravel-Backpack/community-forum/assets/64080305/87362794-e1c8-4e63-9194-8a6c8790f868)

![image](https://github.com/Laravel-Backpack/community-forum/assets/64080305/798c1170-58d7-4266-8a6c-1d0f6312c04a)

### Is it a bug in the latest version of Backpack? Yes.

After I run ```composer update backpack/crud``` the bug is it still there

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.2.12 (cli) (built: Oct 24 2023 21:15:15) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies

### LARAVEL VERSION:
11.0.6.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.0        
backpack/crud: 6.7.0
backpack/devtools: 3.0.4
backpack/generators: v4.0.4
backpack/pro: 2.1.10
backpack/theme-tabler: 1.2.8

**Comment by jcastroa87** [comment]
Hello @ricoroma-coder 

This problem always happens about not correctly config "APP_URL", after config the correct URL, please clear cache:

```
php artisan config:clear
php artisan cache:clear
php artisan view:clear
php artisan basset:clear
```

If that does not work for you, please try to check the error log and run:
```
php artisan basset:check
```

Check permissions:
```
chmod -R 755 storage

chmod -R 755 vendor

chmod -R 644 bootstrap/caches
```

Finally you can follow other instructions in these issues:

https://github.com/Laravel-Backpack/community-forum/issues/552
https://github.com/Laravel-Backpack/community-forum/discussions/576
https://github.com/Laravel-Backpack/community-forum/discussions/674

Let me know if that works for you; thanks.

Cheers.

**Comment by ricoroma-coder** [comment]
Actually, I realize that I forgot to run 
```php artisan storage:link```

And now, it's working with Docker. But now doesn't work without it. XD
Guess it has something to do with the public disk.

![image](https://github.com/Laravel-Backpack/community-forum/assets/64080305/296c11cd-3ef5-4409-b874-f21480c4e47d)

**Comment by jcastroa87** [comment]
Im glad you solve the problem. I will close the issue, but please feel free to re-open or create a new one.

Cheers.
