### ISSUE TITLE
[Feature Request] Widget for loading a LiveWire component

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#89]
If you're using Livewire in your admin panel (maybe dashboard, maybe elsewhere) we should probably make it dead-simple and consistent to load that component into a page. And I can't think of a better way than using our Widgets.

Plus, you could then use packages that provide certain LiveWire components and use those, instead of building your own. For example https://github.com/asantibanez/livewire-charts

**Comment by LemarinelNet** [comment]
Sure,
I'm diving right into livewire now, and have already a few ideas...
The first that I see, is automatically including livewire styles and scripts on the parent template...

Meanwhile, I don't know how we could integrate livewire in standard crud forms...

Any idea ?

**Comment by tabacitu** [comment]
Neither do I in standard forms, I don't think Livewire makes sense there because it's different UI paradigm:
- livewire - live forms / widgets / etc
- create/update - only save stuff after you click the button at the bottom of the form

There could be other stuff inside forms though, like fields with instant validation. Think of "slug" or smth like that, which will tell you if the slug is unique as you type - that could be genuinely useful I think. That could take the form of a new field... maybe ```live_text```?! Idk.

But mostly I think LiveWire will be useful for live widgets, and for (maybe, at some point) rewriting some of the operations. Like Reorder. Or maybe after a huge effort, even List. Of course, this is a tricky thing to do since not everyone will like LiveWire. So we'd probably need to create _alternative_ operations, something like:
- LiveList
- LiveCreate
- LiveUpdate
- LiveDelete
- LiveReorder
etc.

Those are the wide directions I think we might be able to go. Eager to see what you think @LemarinelNet after giving LiveWire a whirl.

**Comment by LemarinelNet** [comment]
Great to see your thoughts !

I'm really new to livewwire, but worked with it on a new project last two days, so I'm starting to understand a bit more ;)

I find livewire very interresting for backend devs that don't have to understand a sh.t of javascript to make things interactive ! really powerfull !
That's something I like really, I can write many logic from behind the scenes, without typing any single javascript word !
Sometimes , as a great friend of mine said, you have to "unlearn what you learned" before, i.e. to show a modal from backend, just changing a property, and not with javascript...
Well, enough said !

Yes, I think that LiveList and other operations would be the good way to go.
LiveList is probably (as far I understand it) the easiest to start with...

**Comment by tabacitu** [comment]
> Sometimes , as a great friend of mine said, you have to "unlearn what you learned" before, i.e. to show a modal from backend, just changing a property, and not with javascript...

I agree. Good new is that out of all "unlearning" processes... I've found livewire to be the easiest 😀 And there's a special place in my heart for tools that help me eliminate JS code - the more the better 😂

> LiveList is probably (as far I understand it) the easiest to start with...

I see it the other way around - I think that's the most difficult part, due to all the features we've crammed into it over the years. Consider filters, search, pagination, buttons, details_row, responsive_table, searchLogic, orderLogic, columnPriority, etc 🤯

**Comment by tabacitu** [comment]
Done in https://github.com/Laravel-Backpack/CRUD/pull/4971
