### ISSUE TITLE
[Bug] The File/Image validation rule does not work on the Image field

### ISSUE THREAD

**Issue by tringuyenduc2903** [Laravel-Backpack/community-forum#893]
# Bug report

### What I did

Create a field with type **image**

### What I expected to happen

Can Validate with **image** or **file**
```php
public function rules(): array
{
  ...
  'image' => ['image'],
  \\ or 'image' => ['file'],
  ...
}
``` 

### What happened

Only works with type **upload**
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/79140d37-11e7-46d4-a108-2686aad23572)

### What I've already tried to fix it

```php
public function rules(): array
{
  ...
'image' => ['regex:/^data:image/'],
  ...
}
``` 

### Is it a bug in the latest version of Backpack?

After I run backpack ```composer update backpack/crud``` the error it still persists

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:
![image](https://github.com/Laravel-Backpack/community-forum/assets/101564593/b4c51a61-4e3e-4ea3-80ff-37de3869eec7)

**Comment by pxpm** [comment]
Hello @tringuyenduc2903 

Image field sends a base64 string. You need to use a special package to validate image fields. 

We are re-working the whole uploaders system including validation, and will consider creating a ValidationRule for image too.

https://github.com/crazybooot/base64-validation 

I've been using this package with success to validate base64 strings. At the moment it does not support Laravel 11, but there is a branch there already by shift, so you can use that temporary branch until they merge the L11 support.

 Hope it helps 🙏 

Cheers
