### ISSUE TITLE
[Bug] Editable columns update error

### ISSUE THREAD

**Issue by sca1235** [Laravel-Backpack/community-forum#898]
# Bug report

### What I did

Updated to latest versions of backpack editable columns. 3.0.8

### What I expected to happen

save minor update to work

### What happened

production.ERROR: Call to a member function withFakes() on bool {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function withFakes() on bool at /var/www/static/vendor/backpack/editable-columns/src/Http/Controllers/Operations/MinorUpdateOperation.php:95)
[stacktrace]

rest of error log https://codeshare.io/64VkRO

### What I've already tried to fix it

update composer

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

Yes

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### LARAVEL VERSION:
10.48.4.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.0
backpack/crud: 6.7.2
backpack/editable-columns: 3.0.8
backpack/filemanager: 3.0.7
backpack/permissionmanager: 7.2.0
backpack/pro: 2.1.11
backpack/revise-operation: 2.0.0
backpack/theme-coreuiv2: 1.2.3
backpack/theme-tabler: 1.2.8

**Comment by pxpm** [comment]
Hey @sca1235 thanks for the heads up. 🙏 

I've just tagged editable-columns 3.0.9 with the fix. It should take a little bit for our private repository to pick the changes, and you will be able to get the fix with a `composer update`. 

Let me know if you are still experiencing issues after the update. 

Cheers

**Comment by sca1235** [comment]
@pxpm yes fixed thanks

**Comment by allam2002** [comment]
i have the same problem even in the last update

**Comment by pxpm** [comment]
@allam2002 can you check that you have at least 3.0.9 version ? 

You can check your installed version with: `php artisan backpack:version`. 

Cheers

**Comment by allam2002** [comment]
### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.3
backpack/basset: 1.3.4
backpack/crud: 6.7.17
backpack/devtools: 2.0.3
backpack/editable-columns: 3.0.9
backpack/filemanager: 3.0.8
backpack/generators: v4.0.5
backpack/logmanager: v5.0.2
backpack/medialibrary-uploaders: 1.2.0
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.4
backpack/revise-operation: 2.0.0
backpack/theme-tabler: 1.2.10

**Comment by allam2002** [comment]
BACKPACK PACKAGE VERSIONS:

backpack/backupmanager: v5.0.3
backpack/basset: 1.3.4
backpack/crud: 6.7.17
backpack/devtools: 2.0.3
backpack/editable-columns: 3.0.9
backpack/filemanager: 3.0.8
backpack/generators: v4.0.5
backpack/logmanager: v5.0.2
backpack/medialibrary-uploaders: 1.2.0
backpack/permissionmanager: 7.2.1
backpack/pro: 2.2.4
backpack/revise-operation: 2.0.0
backpack/theme-tabler: 1.2.10
