### ISSUE TITLE
[HAS-FIX] ASSETS NOT LOADING FROM CDNS - 12-04-2024

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/community-forum#928]
We are aware of an issue that started today where some CDNs refuse to serve the links with ?extraParameters.

We use a `?nonce=` parameter in our assets for cache-busting.

~~For a WORKAROUND, please add `BASSET_DEV_MODE=false` and cache locally your assets with `php artisan basset:cache` (even in localhost if you want to work until this problem is solved).~~

~~We think this is a TEMPORARY issue and we will keep a close eye on it. 
In case it lasts for more time than expected, we may have to reconsider the usage of the cache busting string and fix it on our side.~~

~~Please remember that if you cache the assets when deploying to production (as you should), we use the local assets, so everything will work just fine.~~

Please do a `composer update` to get CRUD 6.7.6 that will automatically update basset to 1.3.1. 

Let us know if you are still experiencing issues.

**Comment by pxpm** [comment]
Some calls still work, weirdo!
![image](https://github.com/Laravel-Backpack/community-forum/assets/7188159/091de3ad-6e2b-48f6-a033-00d717290269)

For example `https://unpkg.com/noty@3.2.0-beta-deprecated/lib/noty.css?fa587b39e127` returns a redirect to `https://unpkg.com/noty@3.2.0-beta-deprecated/lib/noty.css` while `https://unpkg.com/@tabler/core@1.0.0-beta19/dist/css/tabler.min.css?fa587b39e127` does not redirect a simply fails.

**Comment by dauvray** [comment]
Hello,

php artisan basset:cache  put  'error code: 520'  in files .

**Comment by pxpm** [comment]
@dauvray it's possible that `php artisan basset:check` will return an error that you will need to fix. 

Most likely `APP_URL` in your .env file is not properly set, or if that's a container, you should probably be exposing/using a friendly url like `http://my-project.test`.

Cheers

Cheers

**Comment by pxpm** [comment]
We have released https://github.com/Laravel-Backpack/CRUD/releases/tag/6.7.6 with the fix. 
It should update basset to version 1.3.1.

If anyone still experiencing issues after `composer update` please let us know.

**Comment by rich-williamson** [comment]
I can confirm that has resolved the issue for me.
