### ISSUE TITLE
[Feature Request] Admin Panel Language Picker (Dropdown)

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/community-forum#93]
Allow the developer to easily include a dropdown in the top-right corner, that will allow the admin to pick which language the admin panel is in.

It will probably work with a `middleware` that changes the `app_locale` to that value.

Questions/issues:
1. What do we show inside the datepicker? Flags would require providing the image or loading from CDN. Another option would be to show the language name in native language (ex: instead of `Portuguese` say `Português`)
2. How easy to make it for the developer? Do we ask him to create the middleware and button, or do we provide them and ask him to change a config value?

Not sure this is better as a tutorial, and add-on or as a core feature.

**Comment by promatik** [comment]
I think we could provide something like this;

![image](https://user-images.githubusercontent.com/1838187/98173995-fe728d00-1eeb-11eb-8d4d-7e2450ba82f0.png)

The images aren't a problem, I have 253 flags and it is just 226 KB in total, we could bundle it on packages folder.
But flags represent countries, not languages. (Sometimes we may have to map it `pt_BR => br.png`.

We could use the config.crud.locales to populate this, but I don't recommend it, because developers may want backpack in English and their native locale only, like English and Portuguese, but the content in multiple languages, like [en, pt, es, fr].

I would recommend to start using a package to deal with naming (native and foreign). We could start using a simple package like [league/iso3166](https://packagist.org/packages/league/iso3166) to provide this info to us and stop using it on the `config.crud.locales`.

Countries and locales oficial naming may change, and we shouldn't be worried about keeping that config updated 🤷‍♂️

We could then simplify the config and by default have just this;

```php
// Please use ISO 3166-1 alpha-2 convention (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
'locales' => [
  'backpack' => [
    'en',
  ]
  'content' => [
    'en',
  ]
```

Developers may then add `'en', 'pt', 'pt_BR'`, I would then use league/iso3166 to get the proper names.

What do you think @tabacitu?

**Comment by pxpm** [comment]
> The images aren't a problem, I have 253 flags and it is just 226 KB in total, we could bundle it on packages folder.
> But flags represent countries, not languages. (Sometimes we may have to map it `pt_BR => br.png`.

Can we reduce it even more ? Not sure but maybe using a single svg file with all flags or smth like ?

> We could use the config.crud.locales to populate this, but I don't recommend it, because developers may want backpack in English and their native locale only, like English and Portuguese, but the content in multiple languages, like [en, pt, es, fr].

I think you got a point here. We cannot use `config.crud.locales` as "allowed to edit languages" and "dashboard language" because they maybe be different. Maybe one more config: `edit_content_locales => ['pt', 'en']` and `admin_panel_locales => ['es', 'fr']`

**Comment by promatik** [comment]
> Can we reduce it even more ? Not sure but maybe using a single svg file with all flags or smth like ?

226Kb for 252 flags is quite difficult to beat, less than 1Kb/image 😅
Anyway, the images I have are quite small, we should get some with better resolution.

Single files are great, but if you are going to use one or two images (most of the use cases) the end users are going to download the bundle without needing it, and in case of SVG, a single file is the same size as multiple, since it's vector.

> I think you got a point here. We cannot use `config.crud.locales` as "allowed to edit languages" and "dashboard language" because they maybe be different. Maybe one more config: `edit_content_locales => ['pt', 'en']` and `admin_panel_locales => ['es', 'fr']`

So do you agree with removing the current `config.crud.locales`? And using some package to provide the mapping to ISO 3166-1 names?

**Comment by iMokhles** [comment]
I already implemented this

![Capture d’écran 2020-11-06 à 22 21 15](https://user-images.githubusercontent.com/1247248/98415888-63f68300-207e-11eb-9265-5109d2b1ce8b.png)

**Comment by iMokhles** [comment]
Here's how i implemented it

my middleware

```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Session;

class Languages
{
    /**
     * Handle an incoming request.
     *
     * @param $request
     * @param Closure $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $localKey = 'applocale';

        if (Session::has($localKey)
            && array_key_exists(
                Session::get($localKey),
                Config::get('langs')
            )) {
            App::setLocale(Session::get($localKey));
        } else { // This is optional as Laravel will automatically set the fallback language if there is none specified
            Session::put($localKey, Config::get('app.fallback_locale'));
            App::setLocale(Config::get('app.fallback_locale'));
        }
        return $next($request);
    }
}

```

my langs.php config file
```
<?php


return [
    'en' => 'English',
    'fr' => 'Français',
    'ar' => 'العربية'
    ];
```

route inside web.php

`Route::get('lang/{lang}', 'LocalizeController@index')->name('lang.set');`

my controller

```
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

class LocalizeController extends Controller
{
    private $localKey = 'applocale';

    public function index(Request $request, $lang)
    {

        if (array_key_exists($lang, Config::get('langs'))) {
            Session::put($this->localKey, $lang);
        }
        return Redirect::back();

    }
}
```

my middlewares kernel i updated only `$middlewareGroups`

```
    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,

            Languages::class,
        ],

        'api' => [
            'throttle:api',
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],
    ];
```

hope it helps you

**Comment by tabacitu** [comment]
Thanks a lot for the code @iMokhles - will definitely help. I love how you and @promatik  implemented it with flags, but I think @promatik brings an excellent point [here](https://github.com/Laravel-Backpack/ideas/issues/93#issuecomment-722027786):

> But flags represent countries, not languages. (Sometimes we may have to map it pt_BR => br.png)

That's... totally right 🤣 I didn't think of that.

> I would recommend to start using a package to deal with naming (native and foreign). We could start using a simple package like league/iso3166 to provide this info to us and stop using it on the `config.crud.locales`.
> Countries and locales oficial naming may change, and we shouldn't be worried about keeping that config updated 🤷‍♂️

I would totally want that. However:
- in v4.2 I don't think it's the right time to considerably change the config file; maybe something for v12 instead;
- afaik iso3166 deals with countries, not languages; there should be an ISO and PHP package for languages though... right?!

> We could use the config.crud.locales to populate this, but I don't recommend it, because developers may want backpack in English and their native locale only, like English and Portuguese, but the content in multiple languages, like [en, pt, es, fr].

Right. I agree. In addition, because the config is inside `crud.php` not `base.php` it feels a bit off to use that config in someting that has nothing to do with CRUDs...

## Conclusions

So for now, in 4.2, I think:
- flags _indeed_ provide a better visual cue; but they also add a lot of complexity for that visual cue (need flag images, need us to map languages to countries);
- having a dropdown with _just the languages_ would be much _much_ easier to create;
- having _languages_ inside the dropdown is a must _even if_ we add flags; so flags can be added later on;

So I think **we can start with a dropdown that only provides the languages**. In that dropdown:
- we shouldn't use the `backpack.crud.locales` config value; we just ignore that exists;
- we should make sure the strings are translated, so people who have no idea what the current language is can easily switch to their own language (so the string should say `Română (România)` not `Romanian (Romania)`.. or perhaps `中文 (Chinese)` not `Chinese (China)`);
- what we DO store in the cookie/session should still be the Laravel-compatible language string (`pt` or `pt-BR` whatever it is), because we use Laravel to change the app language; whatever standard Laravel is using there, that's what we need to use;
- in terms of how the developer will choose which languages the dropdown to show, we could:
    - (A) add a new config like @pxpm said, but to base, so maybe `backpack.base.interface_locales`
    - (B) allow the developer to choose the languages shown in the dropdown _when they add the dropdown to their HTML_;

## Next steps

The nice thing is... if we put together all of the above (using solution B), this ends up being _super_ self-contained! Something that can easily be provided as a 1st party Backpack add-on, since it will just have:
- a middleware, so that 
    - if `?backpack_interface_language=pt` is ever present, it will add a cookie that remembers that;
    - if the cookie is present, sets the Laravel app language to whatever is inside that cookie;
- a blade file, that 
    - contains the HTML needed
    - contains the list of all language strings (translated), that you can add to your menu (either loaded from a 3rd party package or just like that as a PHP/JS array);

And the steps to add this non-default functionality to your Backpack admin would be to:
- `composer require backpack/multi-language-interface`;
- add the middleware to your `config/backpack/base` inside `middleware_class`;
- inside your `resources/views/vendor/backpack/base/inc/topbar_right_content.blade.php` add `@include('backpack::inc.interface_language_dropdown', ['en', 'pt', 'fr', 'it'])` - you specify what languages you want the dropdown to have right there;

Thoughts?

**Comment by iMokhles** [comment]
Here's a new concept with only languages names ( translated )
![Capture d’écran 2020-11-08 à 21 57 50](https://user-images.githubusercontent.com/1247248/98484122-9387c580-220d-11eb-81ae-0a8aa32934bd.png)

modified topbar_right_content.blade.php code

```
@php
    $localKey = 'applocale';
@endphp
@php
    $htmlDir = config('backpack.base.html_direction');
    if(session('applocale') === 'ar') {
        $htmlDir = 'rtl';
    }
@endphp

<li class="nav-item dropdown pr-4">
    <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
    @if(session($localKey) === 'fr')
            @lang('admin.french', [], 'fr')
        @elseif(session($localKey) === 'ar')
            @lang('admin.arabic', [], 'ar')
        @else
            @lang('admin.english', [], 'en')
        @endif
    </a>
    <div class="dropdown-menu {{ $htmlDir == 'rtl' ? 'dropdown-menu-left' : 'dropdown-menu-right' }} mr-4 pb-1 pt-1">
        <a class="dropdown-item @if(session($localKey) === 'ar') active @endif" href="{{route('lang.set', ['ar'])}}"> @lang('admin.arabic', [], 'ar')</a>
        <a class="dropdown-item @if(session($localKey) === 'en') active @endif" href="{{route('lang.set', ['en'])}}"> @lang('admin.english', [], 'en')</a>
        <a class="dropdown-item @if(session($localKey) === 'fr') active @endif " href="{{route('lang.set', ['fr'])}}"> @lang('admin.french', [], 'fr')</a>
    </div>
</li>
```

**Comment by blondie63** [comment]
Is there a sample project with this language selector to download ?
Thanks :)

**Comment by blondie63** [comment]
> https://github.com/Laravel-Backpack/multi-language

Is this a future link ? now 404 :)

**Comment by promatik** [comment]
Yes, future link, sorry @blondie63 😅
It's still being tested, but I hope it will be released soon 👌

**Comment by tabacitu** [comment]
Heads-up, we've renamed it, so the actual link will be https://github.com/laravel-backpack/language-switcher

We will make this public by the end of the week, it's ready so... I'm going to close the issue.

Thanks to everyone who's contributed here 🙏
