### ISSUE TITLE
Problems deploying backpack for Laravel on VPS

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#934]
### Discussed in https://github.com/Laravel-Backpack/community-forum/discussions/933

<div type='discussions-op-text'>

<sup>Originally posted by **AlonMoshe** April 14, 2024</sup>
I am developing a Backpack for Laravel project locally using wamp, visual studio code, and git. In the local environment everything works correctly.

When I try to deploy the Backpack for Laravel project on a VPS, it doesn't work. That is, when I browse to the URL of the project: https://example.com/, I see the Laravel page of a new project. When I browse to https://example.com/admin, I get: "The requested URL was not found on this server", instead of the usual login page of backpack.

These are the steps I followed to deploy the project:

Clone from GitHub

Make relevant changes in .env:

2.1 Change APP_ENV from local to production, 2.2 Change APP_URL, 2.3 Change database credentials

Run migrations

make sure that all the permissions are correct in all directories and subdirectories of the system

composer install

Repeat step 2</div>

**Comment by jcastroa87** [comment]
Close because is duplicate: https://github.com/Laravel-Backpack/community-forum/discussions/933
