### ISSUE TITLE
Store the table schema when initializing the CrudPanel object

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/community-forum#97]
One of the heavy liftings of crud panel is the calls to check types/attributes of columns in database. 

It could really boost our performance if we store the whole table schema in some place that we could query later instead of multiple calls to the db.

**Comment by tabacitu** [comment]
Totally! Let's move this to v4.2 though.

**Comment by pxpm** [comment]
This is done: https://github.com/Laravel-Backpack/CRUD/blob/main/src/app/Library/Database/DatabaseSchema.php
