### ISSUE TITLE
[Bug] SCDM Backpack Admin Panel

### ISSUE THREAD

**Issue by VeronicaCardoni** [Laravel-Backpack/community-forum#986]
# Bug report

### What I did

??
!
<img width="793" alt="Dashboard error 500" src="https://github.com/Laravel-Backpack/community-forum/assets/169896649/8670c24f-b5dd-405e-9a3a-4ce3720ed71f">

### What I expected to happen

??

### What happened

??
Every time I try creating a new account on the Dashboard, I receive the Error 500 message. Can you please help?

### What I've already tried to fix it

??

### Is it a bug in the latest version of Backpack?

After I run ```composer update backpack/crud``` the bug... is it still there?

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

**Comment by pxpm** [comment]
Hello @VeronicaCardoni 

I would advise you to check your model `$fillable` property, It seems the "status" column is not on the list of columns to store in the database. 
Or, you maybe added the field with the wrong name, AFAIK the column in the database is called "status", and you are sending "invoice_status"  (not sure if they are meant to be the same thing). 

Let me know if that helps. 

Cheers

**Comment by VeronicaCardoni** [comment]
Confidential

Dear Pedro,

I was now able to add a user, thank you - however, I tried to add the company's logo but received the same error disclaimer.

Could you please advise?

Thank you,

Veronica Cardoni
She | Her
Association Coordinator

T    +32 2 320 24 92
W   wearemci.com<https://www.wearemci.com/>

MCI Benelux SA
