### ISSUE TITLE
Problems with ckeditor and elfinder

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#988]
Hi Team, i just received this on email:
"Hello, we have pro version license. 

Now we have problem with creditor and elfinder. We already install backpack https://github.com/laravel-backpack/filemanager and already have File manager page and it works https://prnt.sc/aUKWJwut1Sse 
But in ckeditor field we don’t have it, we have this code https://prnt.sc/pGYL6M9gy-mo and it’s the same creditor but with small changes (type=>ckeditor also tried) and on frontend we have this https://prnt.sc/NGvzdN7fQwlk but elfinder is not here. 

We also research code source and in data-options all OK - https://prnt.sc/YzQwM84oX9xG

Can you help me please with this problem? 

Thank you"

**Comment by karandatwani92** [comment]
Hey @backpack-operations 

Sorry for the inconvenience. The CKEditor version upgrade broke elFinder integration.
@pxpm is already working on the fix. We are working on something bigger: AjaxUploader, adding support to other editors, image drag-and-drop feature(similar to the GitHub comment box).


Things are in progress. [WIP] https://github.com/Laravel-Backpack/PRO/pull/217 , https://github.com/Laravel-Backpack/PRO/pull/215
 We'll let you know by leaving an update here, but it may take some time.

**Comment by pxpm** [comment]
Hey @backpack-operations 

we have just released backpack/pro: 2.2.2 that brings back elfinder support to ckeditor. 

Please have a look at the updated docs: https://backpackforlaravel.com/docs/6.x/crud-fields#ckeditor-pro
