### ISSUE TITLE
Error Updating Laravel Backpack from Version 4 to 5 repo acces error

### ISSUE THREAD

**Issue by backpack-operations** [Laravel-Backpack/community-forum#993]
Hello Team, 
I just received this on email, 
"![image](https://github.com/Laravel-Backpack/community-forum/assets/144793034/e9d6e9d6-ea32-4599-ac4f-24d52c2fc1ad)

Why I don't have  access to pro repo
 "repositories": [
        {
            "type": "composer",
            "url": "https://repo.backpackforlaravel.com/"
        }
    ],

"

**Comment by kalex375** [comment]
During the update process, I received the following error message:

```
Failed to execute git clone --mirror -- https://ghp...6y2:x-oauth-basic@github.com/Laravel-Backpack/PRO.git C:/Users/Administrator/AppData/Local/Composer/vcs/git-github.com-Laravel-Backpack-PRO.git/
Cloning into bare repository 'C:/Users/Administrator/AppData/Local/Composer/vcs/git-github.com-Laravel-Backpack-PRO.git'...
remote: Repository not found.
fatal: repository 'https://github.com/Laravel-Backpack/PRO.git/' not found
It appears that the repository could not be found at the specified URL. I have ensured that my credentials and access permissions are correct.

```

I followed the upgrade guide provided at [Upgrade Guide](https://backpackforlaravel.com/docs/5.x/upgrade-guide) and added the

```
composer config http-basic.backpackforlaravel.com 92881900 XXXXXXXXX
```
As result I have `auth.json` in the root folder.

Our license is registered under the email address [development@appfront.cloud](mailto:development@appfront.cloud).

**Comment by kalex375** [comment]
It works. Thanks for your help.
